/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-07-22 21:53:01 UTC)
 * on 2014-08-07 at 20:02:06 UTC 
 * Modify at your own risk.
 */

package com.fortmin.proshopping.logica.seguridad;

/**
 * Service definition for Seguridad (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link SeguridadRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Seguridad extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.16.0-rc of the seguridad library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://fortminproshop.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "seguridad/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Seguridad(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Seguridad(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "loginUsuario".
   *
   * This request holds the parameters needed by the the seguridad server.  After setting any optional
   * parameters, call the {@link LoginUsuario#execute()} method to invoke the remote operation.
   *
   * @param password
   * @param usuario
   * @return the request
   */
  public LoginUsuario loginUsuario(java.lang.String password, java.lang.String usuario) throws java.io.IOException {
    LoginUsuario result = new LoginUsuario(password, usuario);
    initialize(result);
    return result;
  }

  public class LoginUsuario extends SeguridadRequest<com.fortmin.proshopping.logica.seguridad.model.Mensaje> {

    private static final String REST_PATH = "login_usuario";

    /**
     * Create a request for the method "loginUsuario".
     *
     * This request holds the parameters needed by the the seguridad server.  After setting any
     * optional parameters, call the {@link LoginUsuario#execute()} method to invoke the remote
     * operation. <p> {@link
     * LoginUsuario#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param password
     * @param usuario
     * @since 1.13
     */
    protected LoginUsuario(java.lang.String password, java.lang.String usuario) {
      super(Seguridad.this, "POST", REST_PATH, null, com.fortmin.proshopping.logica.seguridad.model.Mensaje.class);
      this.password = com.google.api.client.util.Preconditions.checkNotNull(password, "Required parameter password must be specified.");
      this.usuario = com.google.api.client.util.Preconditions.checkNotNull(usuario, "Required parameter usuario must be specified.");
    }

    @Override
    public LoginUsuario setAlt(java.lang.String alt) {
      return (LoginUsuario) super.setAlt(alt);
    }

    @Override
    public LoginUsuario setFields(java.lang.String fields) {
      return (LoginUsuario) super.setFields(fields);
    }

    @Override
    public LoginUsuario setKey(java.lang.String key) {
      return (LoginUsuario) super.setKey(key);
    }

    @Override
    public LoginUsuario setOauthToken(java.lang.String oauthToken) {
      return (LoginUsuario) super.setOauthToken(oauthToken);
    }

    @Override
    public LoginUsuario setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (LoginUsuario) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public LoginUsuario setQuotaUser(java.lang.String quotaUser) {
      return (LoginUsuario) super.setQuotaUser(quotaUser);
    }

    @Override
    public LoginUsuario setUserIp(java.lang.String userIp) {
      return (LoginUsuario) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String password;

    /**

     */
    public java.lang.String getPassword() {
      return password;
    }

    public LoginUsuario setPassword(java.lang.String password) {
      this.password = password;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String usuario;

    /**

     */
    public java.lang.String getUsuario() {
      return usuario;
    }

    public LoginUsuario setUsuario(java.lang.String usuario) {
      this.usuario = usuario;
      return this;
    }

    @Override
    public LoginUsuario set(String parameterName, Object value) {
      return (LoginUsuario) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "logoffUsuario".
   *
   * This request holds the parameters needed by the the seguridad server.  After setting any optional
   * parameters, call the {@link LogoffUsuario#execute()} method to invoke the remote operation.
   *
   * @param password
   * @param usuario
   * @return the request
   */
  public LogoffUsuario logoffUsuario(java.lang.String password, java.lang.String usuario) throws java.io.IOException {
    LogoffUsuario result = new LogoffUsuario(password, usuario);
    initialize(result);
    return result;
  }

  public class LogoffUsuario extends SeguridadRequest<com.fortmin.proshopping.logica.seguridad.model.Mensaje> {

    private static final String REST_PATH = "logoff_usuario";

    /**
     * Create a request for the method "logoffUsuario".
     *
     * This request holds the parameters needed by the the seguridad server.  After setting any
     * optional parameters, call the {@link LogoffUsuario#execute()} method to invoke the remote
     * operation. <p> {@link LogoffUsuario#initialize(com.google.api.client.googleapis.services.Abstra
     * ctGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param password
     * @param usuario
     * @since 1.13
     */
    protected LogoffUsuario(java.lang.String password, java.lang.String usuario) {
      super(Seguridad.this, "POST", REST_PATH, null, com.fortmin.proshopping.logica.seguridad.model.Mensaje.class);
      this.password = com.google.api.client.util.Preconditions.checkNotNull(password, "Required parameter password must be specified.");
      this.usuario = com.google.api.client.util.Preconditions.checkNotNull(usuario, "Required parameter usuario must be specified.");
    }

    @Override
    public LogoffUsuario setAlt(java.lang.String alt) {
      return (LogoffUsuario) super.setAlt(alt);
    }

    @Override
    public LogoffUsuario setFields(java.lang.String fields) {
      return (LogoffUsuario) super.setFields(fields);
    }

    @Override
    public LogoffUsuario setKey(java.lang.String key) {
      return (LogoffUsuario) super.setKey(key);
    }

    @Override
    public LogoffUsuario setOauthToken(java.lang.String oauthToken) {
      return (LogoffUsuario) super.setOauthToken(oauthToken);
    }

    @Override
    public LogoffUsuario setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (LogoffUsuario) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public LogoffUsuario setQuotaUser(java.lang.String quotaUser) {
      return (LogoffUsuario) super.setQuotaUser(quotaUser);
    }

    @Override
    public LogoffUsuario setUserIp(java.lang.String userIp) {
      return (LogoffUsuario) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String password;

    /**

     */
    public java.lang.String getPassword() {
      return password;
    }

    public LogoffUsuario setPassword(java.lang.String password) {
      this.password = password;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String usuario;

    /**

     */
    public java.lang.String getUsuario() {
      return usuario;
    }

    public LogoffUsuario setUsuario(java.lang.String usuario) {
      this.usuario = usuario;
      return this;
    }

    @Override
    public LogoffUsuario set(String parameterName, Object value) {
      return (LogoffUsuario) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "registroUsuario".
   *
   * This request holds the parameters needed by the the seguridad server.  After setting any optional
   * parameters, call the {@link RegistroUsuario#execute()} method to invoke the remote operation.
   *
   * @param email
   * @param nombre
   * @param usuario
   * @return the request
   */
  public RegistroUsuario registroUsuario(java.lang.String email, java.lang.String nombre, java.lang.String usuario) throws java.io.IOException {
    RegistroUsuario result = new RegistroUsuario(email, nombre, usuario);
    initialize(result);
    return result;
  }

  public class RegistroUsuario extends SeguridadRequest<com.fortmin.proshopping.logica.seguridad.model.Mensaje> {

    private static final String REST_PATH = "registro_usuario";

    /**
     * Create a request for the method "registroUsuario".
     *
     * This request holds the parameters needed by the the seguridad server.  After setting any
     * optional parameters, call the {@link RegistroUsuario#execute()} method to invoke the remote
     * operation. <p> {@link RegistroUsuario#initialize(com.google.api.client.googleapis.services.Abst
     * ractGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param email
     * @param nombre
     * @param usuario
     * @since 1.13
     */
    protected RegistroUsuario(java.lang.String email, java.lang.String nombre, java.lang.String usuario) {
      super(Seguridad.this, "POST", REST_PATH, null, com.fortmin.proshopping.logica.seguridad.model.Mensaje.class);
      this.email = com.google.api.client.util.Preconditions.checkNotNull(email, "Required parameter email must be specified.");
      this.nombre = com.google.api.client.util.Preconditions.checkNotNull(nombre, "Required parameter nombre must be specified.");
      this.usuario = com.google.api.client.util.Preconditions.checkNotNull(usuario, "Required parameter usuario must be specified.");
    }

    @Override
    public RegistroUsuario setAlt(java.lang.String alt) {
      return (RegistroUsuario) super.setAlt(alt);
    }

    @Override
    public RegistroUsuario setFields(java.lang.String fields) {
      return (RegistroUsuario) super.setFields(fields);
    }

    @Override
    public RegistroUsuario setKey(java.lang.String key) {
      return (RegistroUsuario) super.setKey(key);
    }

    @Override
    public RegistroUsuario setOauthToken(java.lang.String oauthToken) {
      return (RegistroUsuario) super.setOauthToken(oauthToken);
    }

    @Override
    public RegistroUsuario setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (RegistroUsuario) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public RegistroUsuario setQuotaUser(java.lang.String quotaUser) {
      return (RegistroUsuario) super.setQuotaUser(quotaUser);
    }

    @Override
    public RegistroUsuario setUserIp(java.lang.String userIp) {
      return (RegistroUsuario) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String email;

    /**

     */
    public java.lang.String getEmail() {
      return email;
    }

    public RegistroUsuario setEmail(java.lang.String email) {
      this.email = email;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String nombre;

    /**

     */
    public java.lang.String getNombre() {
      return nombre;
    }

    public RegistroUsuario setNombre(java.lang.String nombre) {
      this.nombre = nombre;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String usuario;

    /**

     */
    public java.lang.String getUsuario() {
      return usuario;
    }

    public RegistroUsuario setUsuario(java.lang.String usuario) {
      this.usuario = usuario;
      return this;
    }

    @Override
    public RegistroUsuario set(String parameterName, Object value) {
      return (RegistroUsuario) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Seguridad}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Seguridad}. */
    @Override
    public Seguridad build() {
      return new Seguridad(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link SeguridadRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setSeguridadRequestInitializer(
        SeguridadRequestInitializer seguridadRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(seguridadRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
