/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-10-28 17:08:27 UTC)
 * on 2014-11-06 at 21:38:57 UTC 
 * Modify at your own risk.
 */

package com.fortmin.proshopping.logica.shopping;

/**
 * Service definition for Shopping (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link ShoppingRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Shopping extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.16.0-rc of the shopping library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://fortminproshop.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "shopping/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Shopping(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Shopping(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "actualizarPosicion".
   *
   * This request holds the parameters needed by the the shopping server.  After setting any optional
   * parameters, call the {@link ActualizarPosicion#execute()} method to invoke the remote operation.
   *
   * @param elementoRF
   * @param tipo
   * @param usuario
   * @return the request
   */
  public ActualizarPosicion actualizarPosicion(java.lang.String elementoRF, java.lang.String tipo, java.lang.String usuario) throws java.io.IOException {
    ActualizarPosicion result = new ActualizarPosicion(elementoRF, tipo, usuario);
    initialize(result);
    return result;
  }

  public class ActualizarPosicion extends ShoppingRequest<com.fortmin.proshopping.logica.shopping.model.Mensaje> {

    private static final String REST_PATH = "actualizar_posicion";

    /**
     * Create a request for the method "actualizarPosicion".
     *
     * This request holds the parameters needed by the the shopping server.  After setting any
     * optional parameters, call the {@link ActualizarPosicion#execute()} method to invoke the remote
     * operation. <p> {@link ActualizarPosicion#initialize(com.google.api.client.googleapis.services.A
     * bstractGoogleClientRequest)} must be called to initialize this instance immediately after
     * invoking the constructor. </p>
     *
     * @param elementoRF
     * @param tipo
     * @param usuario
     * @since 1.13
     */
    protected ActualizarPosicion(java.lang.String elementoRF, java.lang.String tipo, java.lang.String usuario) {
      super(Shopping.this, "POST", REST_PATH, null, com.fortmin.proshopping.logica.shopping.model.Mensaje.class);
      this.elementoRF = com.google.api.client.util.Preconditions.checkNotNull(elementoRF, "Required parameter elementoRF must be specified.");
      this.tipo = com.google.api.client.util.Preconditions.checkNotNull(tipo, "Required parameter tipo must be specified.");
      this.usuario = com.google.api.client.util.Preconditions.checkNotNull(usuario, "Required parameter usuario must be specified.");
    }

    @Override
    public ActualizarPosicion setAlt(java.lang.String alt) {
      return (ActualizarPosicion) super.setAlt(alt);
    }

    @Override
    public ActualizarPosicion setFields(java.lang.String fields) {
      return (ActualizarPosicion) super.setFields(fields);
    }

    @Override
    public ActualizarPosicion setKey(java.lang.String key) {
      return (ActualizarPosicion) super.setKey(key);
    }

    @Override
    public ActualizarPosicion setOauthToken(java.lang.String oauthToken) {
      return (ActualizarPosicion) super.setOauthToken(oauthToken);
    }

    @Override
    public ActualizarPosicion setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ActualizarPosicion) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ActualizarPosicion setQuotaUser(java.lang.String quotaUser) {
      return (ActualizarPosicion) super.setQuotaUser(quotaUser);
    }

    @Override
    public ActualizarPosicion setUserIp(java.lang.String userIp) {
      return (ActualizarPosicion) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String elementoRF;

    /**

     */
    public java.lang.String getElementoRF() {
      return elementoRF;
    }

    public ActualizarPosicion setElementoRF(java.lang.String elementoRF) {
      this.elementoRF = elementoRF;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String tipo;

    /**

     */
    public java.lang.String getTipo() {
      return tipo;
    }

    public ActualizarPosicion setTipo(java.lang.String tipo) {
      this.tipo = tipo;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String usuario;

    /**

     */
    public java.lang.String getUsuario() {
      return usuario;
    }

    public ActualizarPosicion setUsuario(java.lang.String usuario) {
      this.usuario = usuario;
      return this;
    }

    @Override
    public ActualizarPosicion set(String parameterName, Object value) {
      return (ActualizarPosicion) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "agregarItemCarrito".
   *
   * This request holds the parameters needed by the the shopping server.  After setting any optional
   * parameters, call the {@link AgregarItemCarrito#execute()} method to invoke the remote operation.
   *
   * @param paquete
   * @param usuario
   * @return the request
   */
  public AgregarItemCarrito agregarItemCarrito(java.lang.String paquete, java.lang.String usuario) throws java.io.IOException {
    AgregarItemCarrito result = new AgregarItemCarrito(paquete, usuario);
    initialize(result);
    return result;
  }

  public class AgregarItemCarrito extends ShoppingRequest<com.fortmin.proshopping.logica.shopping.model.Mensaje> {

    private static final String REST_PATH = "agregar_item_carrito";

    /**
     * Create a request for the method "agregarItemCarrito".
     *
     * This request holds the parameters needed by the the shopping server.  After setting any
     * optional parameters, call the {@link AgregarItemCarrito#execute()} method to invoke the remote
     * operation. <p> {@link AgregarItemCarrito#initialize(com.google.api.client.googleapis.services.A
     * bstractGoogleClientRequest)} must be called to initialize this instance immediately after
     * invoking the constructor. </p>
     *
     * @param paquete
     * @param usuario
     * @since 1.13
     */
    protected AgregarItemCarrito(java.lang.String paquete, java.lang.String usuario) {
      super(Shopping.this, "POST", REST_PATH, null, com.fortmin.proshopping.logica.shopping.model.Mensaje.class);
      this.paquete = com.google.api.client.util.Preconditions.checkNotNull(paquete, "Required parameter paquete must be specified.");
      this.usuario = com.google.api.client.util.Preconditions.checkNotNull(usuario, "Required parameter usuario must be specified.");
    }

    @Override
    public AgregarItemCarrito setAlt(java.lang.String alt) {
      return (AgregarItemCarrito) super.setAlt(alt);
    }

    @Override
    public AgregarItemCarrito setFields(java.lang.String fields) {
      return (AgregarItemCarrito) super.setFields(fields);
    }

    @Override
    public AgregarItemCarrito setKey(java.lang.String key) {
      return (AgregarItemCarrito) super.setKey(key);
    }

    @Override
    public AgregarItemCarrito setOauthToken(java.lang.String oauthToken) {
      return (AgregarItemCarrito) super.setOauthToken(oauthToken);
    }

    @Override
    public AgregarItemCarrito setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (AgregarItemCarrito) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public AgregarItemCarrito setQuotaUser(java.lang.String quotaUser) {
      return (AgregarItemCarrito) super.setQuotaUser(quotaUser);
    }

    @Override
    public AgregarItemCarrito setUserIp(java.lang.String userIp) {
      return (AgregarItemCarrito) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String paquete;

    /**

     */
    public java.lang.String getPaquete() {
      return paquete;
    }

    public AgregarItemCarrito setPaquete(java.lang.String paquete) {
      this.paquete = paquete;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String usuario;

    /**

     */
    public java.lang.String getUsuario() {
      return usuario;
    }

    public AgregarItemCarrito setUsuario(java.lang.String usuario) {
      this.usuario = usuario;
      return this;
    }

    @Override
    public AgregarItemCarrito set(String parameterName, Object value) {
      return (AgregarItemCarrito) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "agregarPuntos".
   *
   * This request holds the parameters needed by the the shopping server.  After setting any optional
   * parameters, call the {@link AgregarPuntos#execute()} method to invoke the remote operation.
   *
   * @param puntos
   * @param usuario
   * @return the request
   */
  public AgregarPuntos agregarPuntos(java.lang.Integer puntos, java.lang.String usuario) throws java.io.IOException {
    AgregarPuntos result = new AgregarPuntos(puntos, usuario);
    initialize(result);
    return result;
  }

  public class AgregarPuntos extends ShoppingRequest<com.fortmin.proshopping.logica.shopping.model.Mensaje> {

    private static final String REST_PATH = "agregar_puntos";

    /**
     * Create a request for the method "agregarPuntos".
     *
     * This request holds the parameters needed by the the shopping server.  After setting any
     * optional parameters, call the {@link AgregarPuntos#execute()} method to invoke the remote
     * operation. <p> {@link AgregarPuntos#initialize(com.google.api.client.googleapis.services.Abstra
     * ctGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param puntos
     * @param usuario
     * @since 1.13
     */
    protected AgregarPuntos(java.lang.Integer puntos, java.lang.String usuario) {
      super(Shopping.this, "POST", REST_PATH, null, com.fortmin.proshopping.logica.shopping.model.Mensaje.class);
      this.puntos = com.google.api.client.util.Preconditions.checkNotNull(puntos, "Required parameter puntos must be specified.");
      this.usuario = com.google.api.client.util.Preconditions.checkNotNull(usuario, "Required parameter usuario must be specified.");
    }

    @Override
    public AgregarPuntos setAlt(java.lang.String alt) {
      return (AgregarPuntos) super.setAlt(alt);
    }

    @Override
    public AgregarPuntos setFields(java.lang.String fields) {
      return (AgregarPuntos) super.setFields(fields);
    }

    @Override
    public AgregarPuntos setKey(java.lang.String key) {
      return (AgregarPuntos) super.setKey(key);
    }

    @Override
    public AgregarPuntos setOauthToken(java.lang.String oauthToken) {
      return (AgregarPuntos) super.setOauthToken(oauthToken);
    }

    @Override
    public AgregarPuntos setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (AgregarPuntos) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public AgregarPuntos setQuotaUser(java.lang.String quotaUser) {
      return (AgregarPuntos) super.setQuotaUser(quotaUser);
    }

    @Override
    public AgregarPuntos setUserIp(java.lang.String userIp) {
      return (AgregarPuntos) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Integer puntos;

    /**

     */
    public java.lang.Integer getPuntos() {
      return puntos;
    }

    public AgregarPuntos setPuntos(java.lang.Integer puntos) {
      this.puntos = puntos;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String usuario;

    /**

     */
    public java.lang.String getUsuario() {
      return usuario;
    }

    public AgregarPuntos setUsuario(java.lang.String usuario) {
      this.usuario = usuario;
      return this;
    }

    @Override
    public AgregarPuntos set(String parameterName, Object value) {
      return (AgregarPuntos) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "checkoutCarrito".
   *
   * This request holds the parameters needed by the the shopping server.  After setting any optional
   * parameters, call the {@link CheckoutCarrito#execute()} method to invoke the remote operation.
   *
   * @param usuario
   * @return the request
   */
  public CheckoutCarrito checkoutCarrito(java.lang.String usuario) throws java.io.IOException {
    CheckoutCarrito result = new CheckoutCarrito(usuario);
    initialize(result);
    return result;
  }

  public class CheckoutCarrito extends ShoppingRequest<com.fortmin.proshopping.logica.shopping.model.Mensaje> {

    private static final String REST_PATH = "checkout_carrito";

    /**
     * Create a request for the method "checkoutCarrito".
     *
     * This request holds the parameters needed by the the shopping server.  After setting any
     * optional parameters, call the {@link CheckoutCarrito#execute()} method to invoke the remote
     * operation. <p> {@link CheckoutCarrito#initialize(com.google.api.client.googleapis.services.Abst
     * ractGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param usuario
     * @since 1.13
     */
    protected CheckoutCarrito(java.lang.String usuario) {
      super(Shopping.this, "POST", REST_PATH, null, com.fortmin.proshopping.logica.shopping.model.Mensaje.class);
      this.usuario = com.google.api.client.util.Preconditions.checkNotNull(usuario, "Required parameter usuario must be specified.");
    }

    @Override
    public CheckoutCarrito setAlt(java.lang.String alt) {
      return (CheckoutCarrito) super.setAlt(alt);
    }

    @Override
    public CheckoutCarrito setFields(java.lang.String fields) {
      return (CheckoutCarrito) super.setFields(fields);
    }

    @Override
    public CheckoutCarrito setKey(java.lang.String key) {
      return (CheckoutCarrito) super.setKey(key);
    }

    @Override
    public CheckoutCarrito setOauthToken(java.lang.String oauthToken) {
      return (CheckoutCarrito) super.setOauthToken(oauthToken);
    }

    @Override
    public CheckoutCarrito setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (CheckoutCarrito) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public CheckoutCarrito setQuotaUser(java.lang.String quotaUser) {
      return (CheckoutCarrito) super.setQuotaUser(quotaUser);
    }

    @Override
    public CheckoutCarrito setUserIp(java.lang.String userIp) {
      return (CheckoutCarrito) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String usuario;

    /**

     */
    public java.lang.String getUsuario() {
      return usuario;
    }

    public CheckoutCarrito setUsuario(java.lang.String usuario) {
      this.usuario = usuario;
      return this;
    }

    @Override
    public CheckoutCarrito set(String parameterName, Object value) {
      return (CheckoutCarrito) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "egresoEstacionamiento".
   *
   * This request holds the parameters needed by the the shopping server.  After setting any optional
   * parameters, call the {@link EgresoEstacionamiento#execute()} method to invoke the remote
   * operation.
   *
   * @param elementoRF
   * @param usuario
   * @return the request
   */
  public EgresoEstacionamiento egresoEstacionamiento(java.lang.String elementoRF, java.lang.String usuario) throws java.io.IOException {
    EgresoEstacionamiento result = new EgresoEstacionamiento(elementoRF, usuario);
    initialize(result);
    return result;
  }

  public class EgresoEstacionamiento extends ShoppingRequest<com.fortmin.proshopping.logica.shopping.model.Mensaje> {

    private static final String REST_PATH = "egreso_estacionamiento";

    /**
     * Create a request for the method "egresoEstacionamiento".
     *
     * This request holds the parameters needed by the the shopping server.  After setting any
     * optional parameters, call the {@link EgresoEstacionamiento#execute()} method to invoke the
     * remote operation. <p> {@link EgresoEstacionamiento#initialize(com.google.api.client.googleapis.
     * services.AbstractGoogleClientRequest)} must be called to initialize this instance immediately
     * after invoking the constructor. </p>
     *
     * @param elementoRF
     * @param usuario
     * @since 1.13
     */
    protected EgresoEstacionamiento(java.lang.String elementoRF, java.lang.String usuario) {
      super(Shopping.this, "POST", REST_PATH, null, com.fortmin.proshopping.logica.shopping.model.Mensaje.class);
      this.elementoRF = com.google.api.client.util.Preconditions.checkNotNull(elementoRF, "Required parameter elementoRF must be specified.");
      this.usuario = com.google.api.client.util.Preconditions.checkNotNull(usuario, "Required parameter usuario must be specified.");
    }

    @Override
    public EgresoEstacionamiento setAlt(java.lang.String alt) {
      return (EgresoEstacionamiento) super.setAlt(alt);
    }

    @Override
    public EgresoEstacionamiento setFields(java.lang.String fields) {
      return (EgresoEstacionamiento) super.setFields(fields);
    }

    @Override
    public EgresoEstacionamiento setKey(java.lang.String key) {
      return (EgresoEstacionamiento) super.setKey(key);
    }

    @Override
    public EgresoEstacionamiento setOauthToken(java.lang.String oauthToken) {
      return (EgresoEstacionamiento) super.setOauthToken(oauthToken);
    }

    @Override
    public EgresoEstacionamiento setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (EgresoEstacionamiento) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public EgresoEstacionamiento setQuotaUser(java.lang.String quotaUser) {
      return (EgresoEstacionamiento) super.setQuotaUser(quotaUser);
    }

    @Override
    public EgresoEstacionamiento setUserIp(java.lang.String userIp) {
      return (EgresoEstacionamiento) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String elementoRF;

    /**

     */
    public java.lang.String getElementoRF() {
      return elementoRF;
    }

    public EgresoEstacionamiento setElementoRF(java.lang.String elementoRF) {
      this.elementoRF = elementoRF;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String usuario;

    /**

     */
    public java.lang.String getUsuario() {
      return usuario;
    }

    public EgresoEstacionamiento setUsuario(java.lang.String usuario) {
      this.usuario = usuario;
      return this;
    }

    @Override
    public EgresoEstacionamiento set(String parameterName, Object value) {
      return (EgresoEstacionamiento) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "eliminarItemCarrito".
   *
   * This request holds the parameters needed by the the shopping server.  After setting any optional
   * parameters, call the {@link EliminarItemCarrito#execute()} method to invoke the remote operation.
   *
   * @param paquete
   * @param usuario
   * @return the request
   */
  public EliminarItemCarrito eliminarItemCarrito(java.lang.String paquete, java.lang.String usuario) throws java.io.IOException {
    EliminarItemCarrito result = new EliminarItemCarrito(paquete, usuario);
    initialize(result);
    return result;
  }

  public class EliminarItemCarrito extends ShoppingRequest<com.fortmin.proshopping.logica.shopping.model.Mensaje> {

    private static final String REST_PATH = "eliminar_item_carrito";

    /**
     * Create a request for the method "eliminarItemCarrito".
     *
     * This request holds the parameters needed by the the shopping server.  After setting any
     * optional parameters, call the {@link EliminarItemCarrito#execute()} method to invoke the remote
     * operation. <p> {@link EliminarItemCarrito#initialize(com.google.api.client.googleapis.services.
     * AbstractGoogleClientRequest)} must be called to initialize this instance immediately after
     * invoking the constructor. </p>
     *
     * @param paquete
     * @param usuario
     * @since 1.13
     */
    protected EliminarItemCarrito(java.lang.String paquete, java.lang.String usuario) {
      super(Shopping.this, "POST", REST_PATH, null, com.fortmin.proshopping.logica.shopping.model.Mensaje.class);
      this.paquete = com.google.api.client.util.Preconditions.checkNotNull(paquete, "Required parameter paquete must be specified.");
      this.usuario = com.google.api.client.util.Preconditions.checkNotNull(usuario, "Required parameter usuario must be specified.");
    }

    @Override
    public EliminarItemCarrito setAlt(java.lang.String alt) {
      return (EliminarItemCarrito) super.setAlt(alt);
    }

    @Override
    public EliminarItemCarrito setFields(java.lang.String fields) {
      return (EliminarItemCarrito) super.setFields(fields);
    }

    @Override
    public EliminarItemCarrito setKey(java.lang.String key) {
      return (EliminarItemCarrito) super.setKey(key);
    }

    @Override
    public EliminarItemCarrito setOauthToken(java.lang.String oauthToken) {
      return (EliminarItemCarrito) super.setOauthToken(oauthToken);
    }

    @Override
    public EliminarItemCarrito setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (EliminarItemCarrito) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public EliminarItemCarrito setQuotaUser(java.lang.String quotaUser) {
      return (EliminarItemCarrito) super.setQuotaUser(quotaUser);
    }

    @Override
    public EliminarItemCarrito setUserIp(java.lang.String userIp) {
      return (EliminarItemCarrito) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String paquete;

    /**

     */
    public java.lang.String getPaquete() {
      return paquete;
    }

    public EliminarItemCarrito setPaquete(java.lang.String paquete) {
      this.paquete = paquete;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String usuario;

    /**

     */
    public java.lang.String getUsuario() {
      return usuario;
    }

    public EliminarItemCarrito setUsuario(java.lang.String usuario) {
      this.usuario = usuario;
      return this;
    }

    @Override
    public EliminarItemCarrito set(String parameterName, Object value) {
      return (EliminarItemCarrito) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "establecerClienteCerca".
   *
   * This request holds the parameters needed by the the shopping server.  After setting any optional
   * parameters, call the {@link EstablecerClienteCerca#execute()} method to invoke the remote
   * operation.
   *
   * @param elementoRf
   * @param tipo
   * @param usuario
   * @return the request
   */
  public EstablecerClienteCerca establecerClienteCerca(java.lang.String elementoRf, java.lang.String tipo, java.lang.String usuario) throws java.io.IOException {
    EstablecerClienteCerca result = new EstablecerClienteCerca(elementoRf, tipo, usuario);
    initialize(result);
    return result;
  }

  public class EstablecerClienteCerca extends ShoppingRequest<com.fortmin.proshopping.logica.shopping.model.Mensaje> {

    private static final String REST_PATH = "establecer_cliente_cerca";

    /**
     * Create a request for the method "establecerClienteCerca".
     *
     * This request holds the parameters needed by the the shopping server.  After setting any
     * optional parameters, call the {@link EstablecerClienteCerca#execute()} method to invoke the
     * remote operation. <p> {@link EstablecerClienteCerca#initialize(com.google.api.client.googleapis
     * .services.AbstractGoogleClientRequest)} must be called to initialize this instance immediately
     * after invoking the constructor. </p>
     *
     * @param elementoRf
     * @param tipo
     * @param usuario
     * @since 1.13
     */
    protected EstablecerClienteCerca(java.lang.String elementoRf, java.lang.String tipo, java.lang.String usuario) {
      super(Shopping.this, "POST", REST_PATH, null, com.fortmin.proshopping.logica.shopping.model.Mensaje.class);
      this.elementoRf = com.google.api.client.util.Preconditions.checkNotNull(elementoRf, "Required parameter elementoRf must be specified.");
      this.tipo = com.google.api.client.util.Preconditions.checkNotNull(tipo, "Required parameter tipo must be specified.");
      this.usuario = com.google.api.client.util.Preconditions.checkNotNull(usuario, "Required parameter usuario must be specified.");
    }

    @Override
    public EstablecerClienteCerca setAlt(java.lang.String alt) {
      return (EstablecerClienteCerca) super.setAlt(alt);
    }

    @Override
    public EstablecerClienteCerca setFields(java.lang.String fields) {
      return (EstablecerClienteCerca) super.setFields(fields);
    }

    @Override
    public EstablecerClienteCerca setKey(java.lang.String key) {
      return (EstablecerClienteCerca) super.setKey(key);
    }

    @Override
    public EstablecerClienteCerca setOauthToken(java.lang.String oauthToken) {
      return (EstablecerClienteCerca) super.setOauthToken(oauthToken);
    }

    @Override
    public EstablecerClienteCerca setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (EstablecerClienteCerca) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public EstablecerClienteCerca setQuotaUser(java.lang.String quotaUser) {
      return (EstablecerClienteCerca) super.setQuotaUser(quotaUser);
    }

    @Override
    public EstablecerClienteCerca setUserIp(java.lang.String userIp) {
      return (EstablecerClienteCerca) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String elementoRf;

    /**

     */
    public java.lang.String getElementoRf() {
      return elementoRf;
    }

    public EstablecerClienteCerca setElementoRf(java.lang.String elementoRf) {
      this.elementoRf = elementoRf;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String tipo;

    /**

     */
    public java.lang.String getTipo() {
      return tipo;
    }

    public EstablecerClienteCerca setTipo(java.lang.String tipo) {
      this.tipo = tipo;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String usuario;

    /**

     */
    public java.lang.String getUsuario() {
      return usuario;
    }

    public EstablecerClienteCerca setUsuario(java.lang.String usuario) {
      this.usuario = usuario;
      return this;
    }

    @Override
    public EstablecerClienteCerca set(String parameterName, Object value) {
      return (EstablecerClienteCerca) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "establecerVisibilidad".
   *
   * This request holds the parameters needed by the the shopping server.  After setting any optional
   * parameters, call the {@link EstablecerVisibilidad#execute()} method to invoke the remote
   * operation.
   *
   * @param usuario
   * @param visible
   * @return the request
   */
  public EstablecerVisibilidad establecerVisibilidad(java.lang.String usuario, java.lang.Boolean visible) throws java.io.IOException {
    EstablecerVisibilidad result = new EstablecerVisibilidad(usuario, visible);
    initialize(result);
    return result;
  }

  public class EstablecerVisibilidad extends ShoppingRequest<com.fortmin.proshopping.logica.shopping.model.Mensaje> {

    private static final String REST_PATH = "establecer_visibilidad";

    /**
     * Create a request for the method "establecerVisibilidad".
     *
     * This request holds the parameters needed by the the shopping server.  After setting any
     * optional parameters, call the {@link EstablecerVisibilidad#execute()} method to invoke the
     * remote operation. <p> {@link EstablecerVisibilidad#initialize(com.google.api.client.googleapis.
     * services.AbstractGoogleClientRequest)} must be called to initialize this instance immediately
     * after invoking the constructor. </p>
     *
     * @param usuario
     * @param visible
     * @since 1.13
     */
    protected EstablecerVisibilidad(java.lang.String usuario, java.lang.Boolean visible) {
      super(Shopping.this, "POST", REST_PATH, null, com.fortmin.proshopping.logica.shopping.model.Mensaje.class);
      this.usuario = com.google.api.client.util.Preconditions.checkNotNull(usuario, "Required parameter usuario must be specified.");
      this.visible = com.google.api.client.util.Preconditions.checkNotNull(visible, "Required parameter visible must be specified.");
    }

    @Override
    public EstablecerVisibilidad setAlt(java.lang.String alt) {
      return (EstablecerVisibilidad) super.setAlt(alt);
    }

    @Override
    public EstablecerVisibilidad setFields(java.lang.String fields) {
      return (EstablecerVisibilidad) super.setFields(fields);
    }

    @Override
    public EstablecerVisibilidad setKey(java.lang.String key) {
      return (EstablecerVisibilidad) super.setKey(key);
    }

    @Override
    public EstablecerVisibilidad setOauthToken(java.lang.String oauthToken) {
      return (EstablecerVisibilidad) super.setOauthToken(oauthToken);
    }

    @Override
    public EstablecerVisibilidad setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (EstablecerVisibilidad) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public EstablecerVisibilidad setQuotaUser(java.lang.String quotaUser) {
      return (EstablecerVisibilidad) super.setQuotaUser(quotaUser);
    }

    @Override
    public EstablecerVisibilidad setUserIp(java.lang.String userIp) {
      return (EstablecerVisibilidad) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String usuario;

    /**

     */
    public java.lang.String getUsuario() {
      return usuario;
    }

    public EstablecerVisibilidad setUsuario(java.lang.String usuario) {
      this.usuario = usuario;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Boolean visible;

    /**

     */
    public java.lang.Boolean getVisible() {
      return visible;
    }

    public EstablecerVisibilidad setVisible(java.lang.Boolean visible) {
      this.visible = visible;
      return this;
    }

    @Override
    public EstablecerVisibilidad set(String parameterName, Object value) {
      return (EstablecerVisibilidad) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "getCalibradoBeacon".
   *
   * This request holds the parameters needed by the the shopping server.  After setting any optional
   * parameters, call the {@link GetCalibradoBeacon#execute()} method to invoke the remote operation.
   *
   * @param elementoRF
   * @return the request
   */
  public GetCalibradoBeacon getCalibradoBeacon(java.lang.String elementoRF) throws java.io.IOException {
    GetCalibradoBeacon result = new GetCalibradoBeacon(elementoRF);
    initialize(result);
    return result;
  }

  public class GetCalibradoBeacon extends ShoppingRequest<com.fortmin.proshopping.logica.shopping.model.Mensaje> {

    private static final String REST_PATH = "get_calibrado_beacon";

    /**
     * Create a request for the method "getCalibradoBeacon".
     *
     * This request holds the parameters needed by the the shopping server.  After setting any
     * optional parameters, call the {@link GetCalibradoBeacon#execute()} method to invoke the remote
     * operation. <p> {@link GetCalibradoBeacon#initialize(com.google.api.client.googleapis.services.A
     * bstractGoogleClientRequest)} must be called to initialize this instance immediately after
     * invoking the constructor. </p>
     *
     * @param elementoRF
     * @since 1.13
     */
    protected GetCalibradoBeacon(java.lang.String elementoRF) {
      super(Shopping.this, "GET", REST_PATH, null, com.fortmin.proshopping.logica.shopping.model.Mensaje.class);
      this.elementoRF = com.google.api.client.util.Preconditions.checkNotNull(elementoRF, "Required parameter elementoRF must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetCalibradoBeacon setAlt(java.lang.String alt) {
      return (GetCalibradoBeacon) super.setAlt(alt);
    }

    @Override
    public GetCalibradoBeacon setFields(java.lang.String fields) {
      return (GetCalibradoBeacon) super.setFields(fields);
    }

    @Override
    public GetCalibradoBeacon setKey(java.lang.String key) {
      return (GetCalibradoBeacon) super.setKey(key);
    }

    @Override
    public GetCalibradoBeacon setOauthToken(java.lang.String oauthToken) {
      return (GetCalibradoBeacon) super.setOauthToken(oauthToken);
    }

    @Override
    public GetCalibradoBeacon setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetCalibradoBeacon) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetCalibradoBeacon setQuotaUser(java.lang.String quotaUser) {
      return (GetCalibradoBeacon) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetCalibradoBeacon setUserIp(java.lang.String userIp) {
      return (GetCalibradoBeacon) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String elementoRF;

    /**

     */
    public java.lang.String getElementoRF() {
      return elementoRF;
    }

    public GetCalibradoBeacon setElementoRF(java.lang.String elementoRF) {
      this.elementoRF = elementoRF;
      return this;
    }

    @Override
    public GetCalibradoBeacon set(String parameterName, Object value) {
      return (GetCalibradoBeacon) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "getCarritoCompleto".
   *
   * This request holds the parameters needed by the the shopping server.  After setting any optional
   * parameters, call the {@link GetCarritoCompleto#execute()} method to invoke the remote operation.
   *
   * @param usuario
   * @return the request
   */
  public GetCarritoCompleto getCarritoCompleto(java.lang.String usuario) throws java.io.IOException {
    GetCarritoCompleto result = new GetCarritoCompleto(usuario);
    initialize(result);
    return result;
  }

  public class GetCarritoCompleto extends ShoppingRequest<com.fortmin.proshopping.logica.shopping.model.CarritoVO> {

    private static final String REST_PATH = "get_carrito_completo";

    /**
     * Create a request for the method "getCarritoCompleto".
     *
     * This request holds the parameters needed by the the shopping server.  After setting any
     * optional parameters, call the {@link GetCarritoCompleto#execute()} method to invoke the remote
     * operation. <p> {@link GetCarritoCompleto#initialize(com.google.api.client.googleapis.services.A
     * bstractGoogleClientRequest)} must be called to initialize this instance immediately after
     * invoking the constructor. </p>
     *
     * @param usuario
     * @since 1.13
     */
    protected GetCarritoCompleto(java.lang.String usuario) {
      super(Shopping.this, "GET", REST_PATH, null, com.fortmin.proshopping.logica.shopping.model.CarritoVO.class);
      this.usuario = com.google.api.client.util.Preconditions.checkNotNull(usuario, "Required parameter usuario must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetCarritoCompleto setAlt(java.lang.String alt) {
      return (GetCarritoCompleto) super.setAlt(alt);
    }

    @Override
    public GetCarritoCompleto setFields(java.lang.String fields) {
      return (GetCarritoCompleto) super.setFields(fields);
    }

    @Override
    public GetCarritoCompleto setKey(java.lang.String key) {
      return (GetCarritoCompleto) super.setKey(key);
    }

    @Override
    public GetCarritoCompleto setOauthToken(java.lang.String oauthToken) {
      return (GetCarritoCompleto) super.setOauthToken(oauthToken);
    }

    @Override
    public GetCarritoCompleto setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetCarritoCompleto) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetCarritoCompleto setQuotaUser(java.lang.String quotaUser) {
      return (GetCarritoCompleto) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetCarritoCompleto setUserIp(java.lang.String userIp) {
      return (GetCarritoCompleto) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String usuario;

    /**

     */
    public java.lang.String getUsuario() {
      return usuario;
    }

    public GetCarritoCompleto setUsuario(java.lang.String usuario) {
      this.usuario = usuario;
      return this;
    }

    @Override
    public GetCarritoCompleto set(String parameterName, Object value) {
      return (GetCarritoCompleto) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "getClienteCerca".
   *
   * This request holds the parameters needed by the the shopping server.  After setting any optional
   * parameters, call the {@link GetClienteCerca#execute()} method to invoke the remote operation.
   *
   * @param elementoRf
   * @param tipo
   * @return the request
   */
  public GetClienteCerca getClienteCerca(java.lang.String elementoRf, java.lang.String tipo) throws java.io.IOException {
    GetClienteCerca result = new GetClienteCerca(elementoRf, tipo);
    initialize(result);
    return result;
  }

  public class GetClienteCerca extends ShoppingRequest<com.fortmin.proshopping.logica.shopping.model.Mensaje> {

    private static final String REST_PATH = "get_cliente_cerca";

    /**
     * Create a request for the method "getClienteCerca".
     *
     * This request holds the parameters needed by the the shopping server.  After setting any
     * optional parameters, call the {@link GetClienteCerca#execute()} method to invoke the remote
     * operation. <p> {@link GetClienteCerca#initialize(com.google.api.client.googleapis.services.Abst
     * ractGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param elementoRf
     * @param tipo
     * @since 1.13
     */
    protected GetClienteCerca(java.lang.String elementoRf, java.lang.String tipo) {
      super(Shopping.this, "GET", REST_PATH, null, com.fortmin.proshopping.logica.shopping.model.Mensaje.class);
      this.elementoRf = com.google.api.client.util.Preconditions.checkNotNull(elementoRf, "Required parameter elementoRf must be specified.");
      this.tipo = com.google.api.client.util.Preconditions.checkNotNull(tipo, "Required parameter tipo must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetClienteCerca setAlt(java.lang.String alt) {
      return (GetClienteCerca) super.setAlt(alt);
    }

    @Override
    public GetClienteCerca setFields(java.lang.String fields) {
      return (GetClienteCerca) super.setFields(fields);
    }

    @Override
    public GetClienteCerca setKey(java.lang.String key) {
      return (GetClienteCerca) super.setKey(key);
    }

    @Override
    public GetClienteCerca setOauthToken(java.lang.String oauthToken) {
      return (GetClienteCerca) super.setOauthToken(oauthToken);
    }

    @Override
    public GetClienteCerca setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetClienteCerca) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetClienteCerca setQuotaUser(java.lang.String quotaUser) {
      return (GetClienteCerca) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetClienteCerca setUserIp(java.lang.String userIp) {
      return (GetClienteCerca) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String elementoRf;

    /**

     */
    public java.lang.String getElementoRf() {
      return elementoRf;
    }

    public GetClienteCerca setElementoRf(java.lang.String elementoRf) {
      this.elementoRf = elementoRf;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String tipo;

    /**

     */
    public java.lang.String getTipo() {
      return tipo;
    }

    public GetClienteCerca setTipo(java.lang.String tipo) {
      this.tipo = tipo;
      return this;
    }

    @Override
    public GetClienteCerca set(String parameterName, Object value) {
      return (GetClienteCerca) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "getCompras".
   *
   * This request holds the parameters needed by the the shopping server.  After setting any optional
   * parameters, call the {@link GetCompras#execute()} method to invoke the remote operation.
   *
   * @param usuario
   * @return the request
   */
  public GetCompras getCompras(java.lang.String usuario) throws java.io.IOException {
    GetCompras result = new GetCompras(usuario);
    initialize(result);
    return result;
  }

  public class GetCompras extends ShoppingRequest<com.fortmin.proshopping.logica.shopping.model.ComprasVOCollection> {

    private static final String REST_PATH = "get_compras";

    /**
     * Create a request for the method "getCompras".
     *
     * This request holds the parameters needed by the the shopping server.  After setting any
     * optional parameters, call the {@link GetCompras#execute()} method to invoke the remote
     * operation. <p> {@link
     * GetCompras#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param usuario
     * @since 1.13
     */
    protected GetCompras(java.lang.String usuario) {
      super(Shopping.this, "GET", REST_PATH, null, com.fortmin.proshopping.logica.shopping.model.ComprasVOCollection.class);
      this.usuario = com.google.api.client.util.Preconditions.checkNotNull(usuario, "Required parameter usuario must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetCompras setAlt(java.lang.String alt) {
      return (GetCompras) super.setAlt(alt);
    }

    @Override
    public GetCompras setFields(java.lang.String fields) {
      return (GetCompras) super.setFields(fields);
    }

    @Override
    public GetCompras setKey(java.lang.String key) {
      return (GetCompras) super.setKey(key);
    }

    @Override
    public GetCompras setOauthToken(java.lang.String oauthToken) {
      return (GetCompras) super.setOauthToken(oauthToken);
    }

    @Override
    public GetCompras setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetCompras) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetCompras setQuotaUser(java.lang.String quotaUser) {
      return (GetCompras) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetCompras setUserIp(java.lang.String userIp) {
      return (GetCompras) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String usuario;

    /**

     */
    public java.lang.String getUsuario() {
      return usuario;
    }

    public GetCompras setUsuario(java.lang.String usuario) {
      this.usuario = usuario;
      return this;
    }

    @Override
    public GetCompras set(String parameterName, Object value) {
      return (GetCompras) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "getPaqueteCompleto".
   *
   * This request holds the parameters needed by the the shopping server.  After setting any optional
   * parameters, call the {@link GetPaqueteCompleto#execute()} method to invoke the remote operation.
   *
   * @param elementoRF
   * @return the request
   */
  public GetPaqueteCompleto getPaqueteCompleto(java.lang.String elementoRF) throws java.io.IOException {
    GetPaqueteCompleto result = new GetPaqueteCompleto(elementoRF);
    initialize(result);
    return result;
  }

  public class GetPaqueteCompleto extends ShoppingRequest<com.fortmin.proshopping.logica.shopping.model.PaqueteVO> {

    private static final String REST_PATH = "get_paquete_completo";

    /**
     * Create a request for the method "getPaqueteCompleto".
     *
     * This request holds the parameters needed by the the shopping server.  After setting any
     * optional parameters, call the {@link GetPaqueteCompleto#execute()} method to invoke the remote
     * operation. <p> {@link GetPaqueteCompleto#initialize(com.google.api.client.googleapis.services.A
     * bstractGoogleClientRequest)} must be called to initialize this instance immediately after
     * invoking the constructor. </p>
     *
     * @param elementoRF
     * @since 1.13
     */
    protected GetPaqueteCompleto(java.lang.String elementoRF) {
      super(Shopping.this, "GET", REST_PATH, null, com.fortmin.proshopping.logica.shopping.model.PaqueteVO.class);
      this.elementoRF = com.google.api.client.util.Preconditions.checkNotNull(elementoRF, "Required parameter elementoRF must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetPaqueteCompleto setAlt(java.lang.String alt) {
      return (GetPaqueteCompleto) super.setAlt(alt);
    }

    @Override
    public GetPaqueteCompleto setFields(java.lang.String fields) {
      return (GetPaqueteCompleto) super.setFields(fields);
    }

    @Override
    public GetPaqueteCompleto setKey(java.lang.String key) {
      return (GetPaqueteCompleto) super.setKey(key);
    }

    @Override
    public GetPaqueteCompleto setOauthToken(java.lang.String oauthToken) {
      return (GetPaqueteCompleto) super.setOauthToken(oauthToken);
    }

    @Override
    public GetPaqueteCompleto setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetPaqueteCompleto) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetPaqueteCompleto setQuotaUser(java.lang.String quotaUser) {
      return (GetPaqueteCompleto) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetPaqueteCompleto setUserIp(java.lang.String userIp) {
      return (GetPaqueteCompleto) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String elementoRF;

    /**

     */
    public java.lang.String getElementoRF() {
      return elementoRF;
    }

    public GetPaqueteCompleto setElementoRF(java.lang.String elementoRF) {
      this.elementoRF = elementoRF;
      return this;
    }

    @Override
    public GetPaqueteCompleto set(String parameterName, Object value) {
      return (GetPaqueteCompleto) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "getPaqueteRf".
   *
   * This request holds the parameters needed by the the shopping server.  After setting any optional
   * parameters, call the {@link GetPaqueteRf#execute()} method to invoke the remote operation.
   *
   * @param elementoRF
   * @return the request
   */
  public GetPaqueteRf getPaqueteRf(java.lang.String elementoRF) throws java.io.IOException {
    GetPaqueteRf result = new GetPaqueteRf(elementoRF);
    initialize(result);
    return result;
  }

  public class GetPaqueteRf extends ShoppingRequest<com.fortmin.proshopping.logica.shopping.model.Paquete> {

    private static final String REST_PATH = "get_paquete_rf";

    /**
     * Create a request for the method "getPaqueteRf".
     *
     * This request holds the parameters needed by the the shopping server.  After setting any
     * optional parameters, call the {@link GetPaqueteRf#execute()} method to invoke the remote
     * operation. <p> {@link
     * GetPaqueteRf#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param elementoRF
     * @since 1.13
     */
    protected GetPaqueteRf(java.lang.String elementoRF) {
      super(Shopping.this, "GET", REST_PATH, null, com.fortmin.proshopping.logica.shopping.model.Paquete.class);
      this.elementoRF = com.google.api.client.util.Preconditions.checkNotNull(elementoRF, "Required parameter elementoRF must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetPaqueteRf setAlt(java.lang.String alt) {
      return (GetPaqueteRf) super.setAlt(alt);
    }

    @Override
    public GetPaqueteRf setFields(java.lang.String fields) {
      return (GetPaqueteRf) super.setFields(fields);
    }

    @Override
    public GetPaqueteRf setKey(java.lang.String key) {
      return (GetPaqueteRf) super.setKey(key);
    }

    @Override
    public GetPaqueteRf setOauthToken(java.lang.String oauthToken) {
      return (GetPaqueteRf) super.setOauthToken(oauthToken);
    }

    @Override
    public GetPaqueteRf setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetPaqueteRf) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetPaqueteRf setQuotaUser(java.lang.String quotaUser) {
      return (GetPaqueteRf) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetPaqueteRf setUserIp(java.lang.String userIp) {
      return (GetPaqueteRf) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String elementoRF;

    /**

     */
    public java.lang.String getElementoRF() {
      return elementoRF;
    }

    public GetPaqueteRf setElementoRF(java.lang.String elementoRF) {
      this.elementoRF = elementoRF;
      return this;
    }

    @Override
    public GetPaqueteRf set(String parameterName, Object value) {
      return (GetPaqueteRf) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "getProductoCompleto".
   *
   * This request holds the parameters needed by the the shopping server.  After setting any optional
   * parameters, call the {@link GetProductoCompleto#execute()} method to invoke the remote operation.
   *
   * @param codigo
   * @param comercio
   * @return the request
   */
  public GetProductoCompleto getProductoCompleto(java.lang.String codigo, java.lang.String comercio) throws java.io.IOException {
    GetProductoCompleto result = new GetProductoCompleto(codigo, comercio);
    initialize(result);
    return result;
  }

  public class GetProductoCompleto extends ShoppingRequest<com.fortmin.proshopping.logica.shopping.model.ProductoExtVO> {

    private static final String REST_PATH = "get_producto_completo";

    /**
     * Create a request for the method "getProductoCompleto".
     *
     * This request holds the parameters needed by the the shopping server.  After setting any
     * optional parameters, call the {@link GetProductoCompleto#execute()} method to invoke the remote
     * operation. <p> {@link GetProductoCompleto#initialize(com.google.api.client.googleapis.services.
     * AbstractGoogleClientRequest)} must be called to initialize this instance immediately after
     * invoking the constructor. </p>
     *
     * @param codigo
     * @param comercio
     * @since 1.13
     */
    protected GetProductoCompleto(java.lang.String codigo, java.lang.String comercio) {
      super(Shopping.this, "GET", REST_PATH, null, com.fortmin.proshopping.logica.shopping.model.ProductoExtVO.class);
      this.codigo = com.google.api.client.util.Preconditions.checkNotNull(codigo, "Required parameter codigo must be specified.");
      this.comercio = com.google.api.client.util.Preconditions.checkNotNull(comercio, "Required parameter comercio must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetProductoCompleto setAlt(java.lang.String alt) {
      return (GetProductoCompleto) super.setAlt(alt);
    }

    @Override
    public GetProductoCompleto setFields(java.lang.String fields) {
      return (GetProductoCompleto) super.setFields(fields);
    }

    @Override
    public GetProductoCompleto setKey(java.lang.String key) {
      return (GetProductoCompleto) super.setKey(key);
    }

    @Override
    public GetProductoCompleto setOauthToken(java.lang.String oauthToken) {
      return (GetProductoCompleto) super.setOauthToken(oauthToken);
    }

    @Override
    public GetProductoCompleto setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetProductoCompleto) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetProductoCompleto setQuotaUser(java.lang.String quotaUser) {
      return (GetProductoCompleto) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetProductoCompleto setUserIp(java.lang.String userIp) {
      return (GetProductoCompleto) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String codigo;

    /**

     */
    public java.lang.String getCodigo() {
      return codigo;
    }

    public GetProductoCompleto setCodigo(java.lang.String codigo) {
      this.codigo = codigo;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String comercio;

    /**

     */
    public java.lang.String getComercio() {
      return comercio;
    }

    public GetProductoCompleto setComercio(java.lang.String comercio) {
      this.comercio = comercio;
      return this;
    }

    @Override
    public GetProductoCompleto set(String parameterName, Object value) {
      return (GetProductoCompleto) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "getProductosPaquete".
   *
   * This request holds the parameters needed by the the shopping server.  After setting any optional
   * parameters, call the {@link GetProductosPaquete#execute()} method to invoke the remote operation.
   *
   * @param paquete
   * @return the request
   */
  public GetProductosPaquete getProductosPaquete(java.lang.String paquete) throws java.io.IOException {
    GetProductosPaquete result = new GetProductosPaquete(paquete);
    initialize(result);
    return result;
  }

  public class GetProductosPaquete extends ShoppingRequest<com.fortmin.proshopping.logica.shopping.model.ProductoCollection> {

    private static final String REST_PATH = "get_productos_paquete";

    /**
     * Create a request for the method "getProductosPaquete".
     *
     * This request holds the parameters needed by the the shopping server.  After setting any
     * optional parameters, call the {@link GetProductosPaquete#execute()} method to invoke the remote
     * operation. <p> {@link GetProductosPaquete#initialize(com.google.api.client.googleapis.services.
     * AbstractGoogleClientRequest)} must be called to initialize this instance immediately after
     * invoking the constructor. </p>
     *
     * @param paquete
     * @since 1.13
     */
    protected GetProductosPaquete(java.lang.String paquete) {
      super(Shopping.this, "GET", REST_PATH, null, com.fortmin.proshopping.logica.shopping.model.ProductoCollection.class);
      this.paquete = com.google.api.client.util.Preconditions.checkNotNull(paquete, "Required parameter paquete must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetProductosPaquete setAlt(java.lang.String alt) {
      return (GetProductosPaquete) super.setAlt(alt);
    }

    @Override
    public GetProductosPaquete setFields(java.lang.String fields) {
      return (GetProductosPaquete) super.setFields(fields);
    }

    @Override
    public GetProductosPaquete setKey(java.lang.String key) {
      return (GetProductosPaquete) super.setKey(key);
    }

    @Override
    public GetProductosPaquete setOauthToken(java.lang.String oauthToken) {
      return (GetProductosPaquete) super.setOauthToken(oauthToken);
    }

    @Override
    public GetProductosPaquete setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetProductosPaquete) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetProductosPaquete setQuotaUser(java.lang.String quotaUser) {
      return (GetProductosPaquete) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetProductosPaquete setUserIp(java.lang.String userIp) {
      return (GetProductosPaquete) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String paquete;

    /**

     */
    public java.lang.String getPaquete() {
      return paquete;
    }

    public GetProductosPaquete setPaquete(java.lang.String paquete) {
      this.paquete = paquete;
      return this;
    }

    @Override
    public GetProductosPaquete set(String parameterName, Object value) {
      return (GetProductosPaquete) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "getPuntajeCliente".
   *
   * This request holds the parameters needed by the the shopping server.  After setting any optional
   * parameters, call the {@link GetPuntajeCliente#execute()} method to invoke the remote operation.
   *
   * @param usuario
   * @return the request
   */
  public GetPuntajeCliente getPuntajeCliente(java.lang.String usuario) throws java.io.IOException {
    GetPuntajeCliente result = new GetPuntajeCliente(usuario);
    initialize(result);
    return result;
  }

  public class GetPuntajeCliente extends ShoppingRequest<com.fortmin.proshopping.logica.shopping.model.Mensaje> {

    private static final String REST_PATH = "get_puntaje_cliente";

    /**
     * Create a request for the method "getPuntajeCliente".
     *
     * This request holds the parameters needed by the the shopping server.  After setting any
     * optional parameters, call the {@link GetPuntajeCliente#execute()} method to invoke the remote
     * operation. <p> {@link GetPuntajeCliente#initialize(com.google.api.client.googleapis.services.Ab
     * stractGoogleClientRequest)} must be called to initialize this instance immediately after
     * invoking the constructor. </p>
     *
     * @param usuario
     * @since 1.13
     */
    protected GetPuntajeCliente(java.lang.String usuario) {
      super(Shopping.this, "GET", REST_PATH, null, com.fortmin.proshopping.logica.shopping.model.Mensaje.class);
      this.usuario = com.google.api.client.util.Preconditions.checkNotNull(usuario, "Required parameter usuario must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetPuntajeCliente setAlt(java.lang.String alt) {
      return (GetPuntajeCliente) super.setAlt(alt);
    }

    @Override
    public GetPuntajeCliente setFields(java.lang.String fields) {
      return (GetPuntajeCliente) super.setFields(fields);
    }

    @Override
    public GetPuntajeCliente setKey(java.lang.String key) {
      return (GetPuntajeCliente) super.setKey(key);
    }

    @Override
    public GetPuntajeCliente setOauthToken(java.lang.String oauthToken) {
      return (GetPuntajeCliente) super.setOauthToken(oauthToken);
    }

    @Override
    public GetPuntajeCliente setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetPuntajeCliente) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetPuntajeCliente setQuotaUser(java.lang.String quotaUser) {
      return (GetPuntajeCliente) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetPuntajeCliente setUserIp(java.lang.String userIp) {
      return (GetPuntajeCliente) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String usuario;

    /**

     */
    public java.lang.String getUsuario() {
      return usuario;
    }

    public GetPuntajeCliente setUsuario(java.lang.String usuario) {
      this.usuario = usuario;
      return this;
    }

    @Override
    public GetPuntajeCliente set(String parameterName, Object value) {
      return (GetPuntajeCliente) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "getTiempoEstacionamiento".
   *
   * This request holds the parameters needed by the the shopping server.  After setting any optional
   * parameters, call the {@link GetTiempoEstacionamiento#execute()} method to invoke the remote
   * operation.
   *
   * @param usuario
   * @return the request
   */
  public GetTiempoEstacionamiento getTiempoEstacionamiento(java.lang.String usuario) throws java.io.IOException {
    GetTiempoEstacionamiento result = new GetTiempoEstacionamiento(usuario);
    initialize(result);
    return result;
  }

  public class GetTiempoEstacionamiento extends ShoppingRequest<com.fortmin.proshopping.logica.shopping.model.EstacionamientoVO> {

    private static final String REST_PATH = "get_tiempo_estacionamiento";

    /**
     * Create a request for the method "getTiempoEstacionamiento".
     *
     * This request holds the parameters needed by the the shopping server.  After setting any
     * optional parameters, call the {@link GetTiempoEstacionamiento#execute()} method to invoke the
     * remote operation. <p> {@link GetTiempoEstacionamiento#initialize(com.google.api.client.googleap
     * is.services.AbstractGoogleClientRequest)} must be called to initialize this instance
     * immediately after invoking the constructor. </p>
     *
     * @param usuario
     * @since 1.13
     */
    protected GetTiempoEstacionamiento(java.lang.String usuario) {
      super(Shopping.this, "GET", REST_PATH, null, com.fortmin.proshopping.logica.shopping.model.EstacionamientoVO.class);
      this.usuario = com.google.api.client.util.Preconditions.checkNotNull(usuario, "Required parameter usuario must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetTiempoEstacionamiento setAlt(java.lang.String alt) {
      return (GetTiempoEstacionamiento) super.setAlt(alt);
    }

    @Override
    public GetTiempoEstacionamiento setFields(java.lang.String fields) {
      return (GetTiempoEstacionamiento) super.setFields(fields);
    }

    @Override
    public GetTiempoEstacionamiento setKey(java.lang.String key) {
      return (GetTiempoEstacionamiento) super.setKey(key);
    }

    @Override
    public GetTiempoEstacionamiento setOauthToken(java.lang.String oauthToken) {
      return (GetTiempoEstacionamiento) super.setOauthToken(oauthToken);
    }

    @Override
    public GetTiempoEstacionamiento setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetTiempoEstacionamiento) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetTiempoEstacionamiento setQuotaUser(java.lang.String quotaUser) {
      return (GetTiempoEstacionamiento) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetTiempoEstacionamiento setUserIp(java.lang.String userIp) {
      return (GetTiempoEstacionamiento) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String usuario;

    /**

     */
    public java.lang.String getUsuario() {
      return usuario;
    }

    public GetTiempoEstacionamiento setUsuario(java.lang.String usuario) {
      this.usuario = usuario;
      return this;
    }

    @Override
    public GetTiempoEstacionamiento set(String parameterName, Object value) {
      return (GetTiempoEstacionamiento) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "getUbicacionCliente".
   *
   * This request holds the parameters needed by the the shopping server.  After setting any optional
   * parameters, call the {@link GetUbicacionCliente#execute()} method to invoke the remote operation.
   *
   * @param usuario
   * @return the request
   */
  public GetUbicacionCliente getUbicacionCliente(java.lang.String usuario) throws java.io.IOException {
    GetUbicacionCliente result = new GetUbicacionCliente(usuario);
    initialize(result);
    return result;
  }

  public class GetUbicacionCliente extends ShoppingRequest<com.fortmin.proshopping.logica.shopping.model.Mensaje> {

    private static final String REST_PATH = "get_ubicacion_cliente";

    /**
     * Create a request for the method "getUbicacionCliente".
     *
     * This request holds the parameters needed by the the shopping server.  After setting any
     * optional parameters, call the {@link GetUbicacionCliente#execute()} method to invoke the remote
     * operation. <p> {@link GetUbicacionCliente#initialize(com.google.api.client.googleapis.services.
     * AbstractGoogleClientRequest)} must be called to initialize this instance immediately after
     * invoking the constructor. </p>
     *
     * @param usuario
     * @since 1.13
     */
    protected GetUbicacionCliente(java.lang.String usuario) {
      super(Shopping.this, "GET", REST_PATH, null, com.fortmin.proshopping.logica.shopping.model.Mensaje.class);
      this.usuario = com.google.api.client.util.Preconditions.checkNotNull(usuario, "Required parameter usuario must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetUbicacionCliente setAlt(java.lang.String alt) {
      return (GetUbicacionCliente) super.setAlt(alt);
    }

    @Override
    public GetUbicacionCliente setFields(java.lang.String fields) {
      return (GetUbicacionCliente) super.setFields(fields);
    }

    @Override
    public GetUbicacionCliente setKey(java.lang.String key) {
      return (GetUbicacionCliente) super.setKey(key);
    }

    @Override
    public GetUbicacionCliente setOauthToken(java.lang.String oauthToken) {
      return (GetUbicacionCliente) super.setOauthToken(oauthToken);
    }

    @Override
    public GetUbicacionCliente setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetUbicacionCliente) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetUbicacionCliente setQuotaUser(java.lang.String quotaUser) {
      return (GetUbicacionCliente) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetUbicacionCliente setUserIp(java.lang.String userIp) {
      return (GetUbicacionCliente) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String usuario;

    /**

     */
    public java.lang.String getUsuario() {
      return usuario;
    }

    public GetUbicacionCliente setUsuario(java.lang.String usuario) {
      this.usuario = usuario;
      return this;
    }

    @Override
    public GetUbicacionCliente set(String parameterName, Object value) {
      return (GetUbicacionCliente) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "getVisibilidadCliente".
   *
   * This request holds the parameters needed by the the shopping server.  After setting any optional
   * parameters, call the {@link GetVisibilidadCliente#execute()} method to invoke the remote
   * operation.
   *
   * @param usuario
   * @return the request
   */
  public GetVisibilidadCliente getVisibilidadCliente(java.lang.String usuario) throws java.io.IOException {
    GetVisibilidadCliente result = new GetVisibilidadCliente(usuario);
    initialize(result);
    return result;
  }

  public class GetVisibilidadCliente extends ShoppingRequest<com.fortmin.proshopping.logica.shopping.model.Mensaje> {

    private static final String REST_PATH = "get_visibilidad_cliente";

    /**
     * Create a request for the method "getVisibilidadCliente".
     *
     * This request holds the parameters needed by the the shopping server.  After setting any
     * optional parameters, call the {@link GetVisibilidadCliente#execute()} method to invoke the
     * remote operation. <p> {@link GetVisibilidadCliente#initialize(com.google.api.client.googleapis.
     * services.AbstractGoogleClientRequest)} must be called to initialize this instance immediately
     * after invoking the constructor. </p>
     *
     * @param usuario
     * @since 1.13
     */
    protected GetVisibilidadCliente(java.lang.String usuario) {
      super(Shopping.this, "GET", REST_PATH, null, com.fortmin.proshopping.logica.shopping.model.Mensaje.class);
      this.usuario = com.google.api.client.util.Preconditions.checkNotNull(usuario, "Required parameter usuario must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetVisibilidadCliente setAlt(java.lang.String alt) {
      return (GetVisibilidadCliente) super.setAlt(alt);
    }

    @Override
    public GetVisibilidadCliente setFields(java.lang.String fields) {
      return (GetVisibilidadCliente) super.setFields(fields);
    }

    @Override
    public GetVisibilidadCliente setKey(java.lang.String key) {
      return (GetVisibilidadCliente) super.setKey(key);
    }

    @Override
    public GetVisibilidadCliente setOauthToken(java.lang.String oauthToken) {
      return (GetVisibilidadCliente) super.setOauthToken(oauthToken);
    }

    @Override
    public GetVisibilidadCliente setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetVisibilidadCliente) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetVisibilidadCliente setQuotaUser(java.lang.String quotaUser) {
      return (GetVisibilidadCliente) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetVisibilidadCliente setUserIp(java.lang.String userIp) {
      return (GetVisibilidadCliente) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String usuario;

    /**

     */
    public java.lang.String getUsuario() {
      return usuario;
    }

    public GetVisibilidadCliente setUsuario(java.lang.String usuario) {
      this.usuario = usuario;
      return this;
    }

    @Override
    public GetVisibilidadCliente set(String parameterName, Object value) {
      return (GetVisibilidadCliente) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "getpaquete".
   *
   * This request holds the parameters needed by the the shopping server.  After setting any optional
   * parameters, call the {@link Getpaquete#execute()} method to invoke the remote operation.
   *
   * @param paquete
   * @return the request
   */
  public Getpaquete getpaquete(java.lang.String paquete) throws java.io.IOException {
    Getpaquete result = new Getpaquete(paquete);
    initialize(result);
    return result;
  }

  public class Getpaquete extends ShoppingRequest<com.fortmin.proshopping.logica.shopping.model.Paquete> {

    private static final String REST_PATH = "get_paquete";

    /**
     * Create a request for the method "getpaquete".
     *
     * This request holds the parameters needed by the the shopping server.  After setting any
     * optional parameters, call the {@link Getpaquete#execute()} method to invoke the remote
     * operation. <p> {@link
     * Getpaquete#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param paquete
     * @since 1.13
     */
    protected Getpaquete(java.lang.String paquete) {
      super(Shopping.this, "GET", REST_PATH, null, com.fortmin.proshopping.logica.shopping.model.Paquete.class);
      this.paquete = com.google.api.client.util.Preconditions.checkNotNull(paquete, "Required parameter paquete must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public Getpaquete setAlt(java.lang.String alt) {
      return (Getpaquete) super.setAlt(alt);
    }

    @Override
    public Getpaquete setFields(java.lang.String fields) {
      return (Getpaquete) super.setFields(fields);
    }

    @Override
    public Getpaquete setKey(java.lang.String key) {
      return (Getpaquete) super.setKey(key);
    }

    @Override
    public Getpaquete setOauthToken(java.lang.String oauthToken) {
      return (Getpaquete) super.setOauthToken(oauthToken);
    }

    @Override
    public Getpaquete setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (Getpaquete) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public Getpaquete setQuotaUser(java.lang.String quotaUser) {
      return (Getpaquete) super.setQuotaUser(quotaUser);
    }

    @Override
    public Getpaquete setUserIp(java.lang.String userIp) {
      return (Getpaquete) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String paquete;

    /**

     */
    public java.lang.String getPaquete() {
      return paquete;
    }

    public Getpaquete setPaquete(java.lang.String paquete) {
      this.paquete = paquete;
      return this;
    }

    @Override
    public Getpaquete set(String parameterName, Object value) {
      return (Getpaquete) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "getubicacion".
   *
   * This request holds the parameters needed by the the shopping server.  After setting any optional
   * parameters, call the {@link Getubicacion#execute()} method to invoke the remote operation.
   *
   * @param ubicacion
   * @return the request
   */
  public Getubicacion getubicacion(java.lang.String ubicacion) throws java.io.IOException {
    Getubicacion result = new Getubicacion(ubicacion);
    initialize(result);
    return result;
  }

  public class Getubicacion extends ShoppingRequest<com.fortmin.proshopping.logica.shopping.model.Ubicacion> {

    private static final String REST_PATH = "get_ubicacion";

    /**
     * Create a request for the method "getubicacion".
     *
     * This request holds the parameters needed by the the shopping server.  After setting any
     * optional parameters, call the {@link Getubicacion#execute()} method to invoke the remote
     * operation. <p> {@link
     * Getubicacion#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param ubicacion
     * @since 1.13
     */
    protected Getubicacion(java.lang.String ubicacion) {
      super(Shopping.this, "GET", REST_PATH, null, com.fortmin.proshopping.logica.shopping.model.Ubicacion.class);
      this.ubicacion = com.google.api.client.util.Preconditions.checkNotNull(ubicacion, "Required parameter ubicacion must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public Getubicacion setAlt(java.lang.String alt) {
      return (Getubicacion) super.setAlt(alt);
    }

    @Override
    public Getubicacion setFields(java.lang.String fields) {
      return (Getubicacion) super.setFields(fields);
    }

    @Override
    public Getubicacion setKey(java.lang.String key) {
      return (Getubicacion) super.setKey(key);
    }

    @Override
    public Getubicacion setOauthToken(java.lang.String oauthToken) {
      return (Getubicacion) super.setOauthToken(oauthToken);
    }

    @Override
    public Getubicacion setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (Getubicacion) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public Getubicacion setQuotaUser(java.lang.String quotaUser) {
      return (Getubicacion) super.setQuotaUser(quotaUser);
    }

    @Override
    public Getubicacion setUserIp(java.lang.String userIp) {
      return (Getubicacion) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String ubicacion;

    /**

     */
    public java.lang.String getUbicacion() {
      return ubicacion;
    }

    public Getubicacion setUbicacion(java.lang.String ubicacion) {
      this.ubicacion = ubicacion;
      return this;
    }

    @Override
    public Getubicacion set(String parameterName, Object value) {
      return (Getubicacion) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "ingresoEstacionamiento".
   *
   * This request holds the parameters needed by the the shopping server.  After setting any optional
   * parameters, call the {@link IngresoEstacionamiento#execute()} method to invoke the remote
   * operation.
   *
   * @param elementoRF
   * @param usuario
   * @return the request
   */
  public IngresoEstacionamiento ingresoEstacionamiento(java.lang.String elementoRF, java.lang.String usuario) throws java.io.IOException {
    IngresoEstacionamiento result = new IngresoEstacionamiento(elementoRF, usuario);
    initialize(result);
    return result;
  }

  public class IngresoEstacionamiento extends ShoppingRequest<com.fortmin.proshopping.logica.shopping.model.Mensaje> {

    private static final String REST_PATH = "ingreso_estacionamiento";

    /**
     * Create a request for the method "ingresoEstacionamiento".
     *
     * This request holds the parameters needed by the the shopping server.  After setting any
     * optional parameters, call the {@link IngresoEstacionamiento#execute()} method to invoke the
     * remote operation. <p> {@link IngresoEstacionamiento#initialize(com.google.api.client.googleapis
     * .services.AbstractGoogleClientRequest)} must be called to initialize this instance immediately
     * after invoking the constructor. </p>
     *
     * @param elementoRF
     * @param usuario
     * @since 1.13
     */
    protected IngresoEstacionamiento(java.lang.String elementoRF, java.lang.String usuario) {
      super(Shopping.this, "POST", REST_PATH, null, com.fortmin.proshopping.logica.shopping.model.Mensaje.class);
      this.elementoRF = com.google.api.client.util.Preconditions.checkNotNull(elementoRF, "Required parameter elementoRF must be specified.");
      this.usuario = com.google.api.client.util.Preconditions.checkNotNull(usuario, "Required parameter usuario must be specified.");
    }

    @Override
    public IngresoEstacionamiento setAlt(java.lang.String alt) {
      return (IngresoEstacionamiento) super.setAlt(alt);
    }

    @Override
    public IngresoEstacionamiento setFields(java.lang.String fields) {
      return (IngresoEstacionamiento) super.setFields(fields);
    }

    @Override
    public IngresoEstacionamiento setKey(java.lang.String key) {
      return (IngresoEstacionamiento) super.setKey(key);
    }

    @Override
    public IngresoEstacionamiento setOauthToken(java.lang.String oauthToken) {
      return (IngresoEstacionamiento) super.setOauthToken(oauthToken);
    }

    @Override
    public IngresoEstacionamiento setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (IngresoEstacionamiento) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public IngresoEstacionamiento setQuotaUser(java.lang.String quotaUser) {
      return (IngresoEstacionamiento) super.setQuotaUser(quotaUser);
    }

    @Override
    public IngresoEstacionamiento setUserIp(java.lang.String userIp) {
      return (IngresoEstacionamiento) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String elementoRF;

    /**

     */
    public java.lang.String getElementoRF() {
      return elementoRF;
    }

    public IngresoEstacionamiento setElementoRF(java.lang.String elementoRF) {
      this.elementoRF = elementoRF;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String usuario;

    /**

     */
    public java.lang.String getUsuario() {
      return usuario;
    }

    public IngresoEstacionamiento setUsuario(java.lang.String usuario) {
      this.usuario = usuario;
      return this;
    }

    @Override
    public IngresoEstacionamiento set(String parameterName, Object value) {
      return (IngresoEstacionamiento) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "quitarPuntos".
   *
   * This request holds the parameters needed by the the shopping server.  After setting any optional
   * parameters, call the {@link QuitarPuntos#execute()} method to invoke the remote operation.
   *
   * @param puntos
   * @param usuario
   * @return the request
   */
  public QuitarPuntos quitarPuntos(java.lang.Integer puntos, java.lang.String usuario) throws java.io.IOException {
    QuitarPuntos result = new QuitarPuntos(puntos, usuario);
    initialize(result);
    return result;
  }

  public class QuitarPuntos extends ShoppingRequest<com.fortmin.proshopping.logica.shopping.model.Mensaje> {

    private static final String REST_PATH = "quitar_puntos";

    /**
     * Create a request for the method "quitarPuntos".
     *
     * This request holds the parameters needed by the the shopping server.  After setting any
     * optional parameters, call the {@link QuitarPuntos#execute()} method to invoke the remote
     * operation. <p> {@link
     * QuitarPuntos#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param puntos
     * @param usuario
     * @since 1.13
     */
    protected QuitarPuntos(java.lang.Integer puntos, java.lang.String usuario) {
      super(Shopping.this, "POST", REST_PATH, null, com.fortmin.proshopping.logica.shopping.model.Mensaje.class);
      this.puntos = com.google.api.client.util.Preconditions.checkNotNull(puntos, "Required parameter puntos must be specified.");
      this.usuario = com.google.api.client.util.Preconditions.checkNotNull(usuario, "Required parameter usuario must be specified.");
    }

    @Override
    public QuitarPuntos setAlt(java.lang.String alt) {
      return (QuitarPuntos) super.setAlt(alt);
    }

    @Override
    public QuitarPuntos setFields(java.lang.String fields) {
      return (QuitarPuntos) super.setFields(fields);
    }

    @Override
    public QuitarPuntos setKey(java.lang.String key) {
      return (QuitarPuntos) super.setKey(key);
    }

    @Override
    public QuitarPuntos setOauthToken(java.lang.String oauthToken) {
      return (QuitarPuntos) super.setOauthToken(oauthToken);
    }

    @Override
    public QuitarPuntos setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (QuitarPuntos) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public QuitarPuntos setQuotaUser(java.lang.String quotaUser) {
      return (QuitarPuntos) super.setQuotaUser(quotaUser);
    }

    @Override
    public QuitarPuntos setUserIp(java.lang.String userIp) {
      return (QuitarPuntos) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Integer puntos;

    /**

     */
    public java.lang.Integer getPuntos() {
      return puntos;
    }

    public QuitarPuntos setPuntos(java.lang.Integer puntos) {
      this.puntos = puntos;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String usuario;

    /**

     */
    public java.lang.String getUsuario() {
      return usuario;
    }

    public QuitarPuntos setUsuario(java.lang.String usuario) {
      this.usuario = usuario;
      return this;
    }

    @Override
    public QuitarPuntos set(String parameterName, Object value) {
      return (QuitarPuntos) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Shopping}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Shopping}. */
    @Override
    public Shopping build() {
      return new Shopping(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link ShoppingRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setShoppingRequestInitializer(
        ShoppingRequestInitializer shoppingRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(shoppingRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
