/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-07-22 21:53:01 UTC)
 * on 2014-07-25 at 22:49:05 UTC 
 * Modify at your own risk.
 */

package com.fortmin.proshopping.logica.shopping;

/**
 * Service definition for Shopping (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link ShoppingRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Shopping extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.16.0-rc of the shopping library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://fortminproshop.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "shopping/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Shopping(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Shopping(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "egresoEstacionamiento".
   *
   * This request holds the parameters needed by the the shopping server.  After setting any optional
   * parameters, call the {@link EgresoEstacionamiento#execute()} method to invoke the remote
   * operation.
   *
   * @param elementoRF
   * @param usuario
   * @return the request
   */
  public EgresoEstacionamiento egresoEstacionamiento(java.lang.String elementoRF, java.lang.String usuario) throws java.io.IOException {
    EgresoEstacionamiento result = new EgresoEstacionamiento(elementoRF, usuario);
    initialize(result);
    return result;
  }

  public class EgresoEstacionamiento extends ShoppingRequest<com.fortmin.proshopping.logica.shopping.model.Mensaje> {

    private static final String REST_PATH = "egreso_estacionamiento";

    /**
     * Create a request for the method "egresoEstacionamiento".
     *
     * This request holds the parameters needed by the the shopping server.  After setting any
     * optional parameters, call the {@link EgresoEstacionamiento#execute()} method to invoke the
     * remote operation. <p> {@link EgresoEstacionamiento#initialize(com.google.api.client.googleapis.
     * services.AbstractGoogleClientRequest)} must be called to initialize this instance immediately
     * after invoking the constructor. </p>
     *
     * @param elementoRF
     * @param usuario
     * @since 1.13
     */
    protected EgresoEstacionamiento(java.lang.String elementoRF, java.lang.String usuario) {
      super(Shopping.this, "POST", REST_PATH, null, com.fortmin.proshopping.logica.shopping.model.Mensaje.class);
      this.elementoRF = com.google.api.client.util.Preconditions.checkNotNull(elementoRF, "Required parameter elementoRF must be specified.");
      this.usuario = com.google.api.client.util.Preconditions.checkNotNull(usuario, "Required parameter usuario must be specified.");
    }

    @Override
    public EgresoEstacionamiento setAlt(java.lang.String alt) {
      return (EgresoEstacionamiento) super.setAlt(alt);
    }

    @Override
    public EgresoEstacionamiento setFields(java.lang.String fields) {
      return (EgresoEstacionamiento) super.setFields(fields);
    }

    @Override
    public EgresoEstacionamiento setKey(java.lang.String key) {
      return (EgresoEstacionamiento) super.setKey(key);
    }

    @Override
    public EgresoEstacionamiento setOauthToken(java.lang.String oauthToken) {
      return (EgresoEstacionamiento) super.setOauthToken(oauthToken);
    }

    @Override
    public EgresoEstacionamiento setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (EgresoEstacionamiento) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public EgresoEstacionamiento setQuotaUser(java.lang.String quotaUser) {
      return (EgresoEstacionamiento) super.setQuotaUser(quotaUser);
    }

    @Override
    public EgresoEstacionamiento setUserIp(java.lang.String userIp) {
      return (EgresoEstacionamiento) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String elementoRF;

    /**

     */
    public java.lang.String getElementoRF() {
      return elementoRF;
    }

    public EgresoEstacionamiento setElementoRF(java.lang.String elementoRF) {
      this.elementoRF = elementoRF;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String usuario;

    /**

     */
    public java.lang.String getUsuario() {
      return usuario;
    }

    public EgresoEstacionamiento setUsuario(java.lang.String usuario) {
      this.usuario = usuario;
      return this;
    }

    @Override
    public EgresoEstacionamiento set(String parameterName, Object value) {
      return (EgresoEstacionamiento) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "establecerVisibilidad".
   *
   * This request holds the parameters needed by the the shopping server.  After setting any optional
   * parameters, call the {@link EstablecerVisibilidad#execute()} method to invoke the remote
   * operation.
   *
   * @param usuario
   * @param visible
   * @return the request
   */
  public EstablecerVisibilidad establecerVisibilidad(java.lang.String usuario, java.lang.Boolean visible) throws java.io.IOException {
    EstablecerVisibilidad result = new EstablecerVisibilidad(usuario, visible);
    initialize(result);
    return result;
  }

  public class EstablecerVisibilidad extends ShoppingRequest<com.fortmin.proshopping.logica.shopping.model.Mensaje> {

    private static final String REST_PATH = "establecer_visibilidad";

    /**
     * Create a request for the method "establecerVisibilidad".
     *
     * This request holds the parameters needed by the the shopping server.  After setting any
     * optional parameters, call the {@link EstablecerVisibilidad#execute()} method to invoke the
     * remote operation. <p> {@link EstablecerVisibilidad#initialize(com.google.api.client.googleapis.
     * services.AbstractGoogleClientRequest)} must be called to initialize this instance immediately
     * after invoking the constructor. </p>
     *
     * @param usuario
     * @param visible
     * @since 1.13
     */
    protected EstablecerVisibilidad(java.lang.String usuario, java.lang.Boolean visible) {
      super(Shopping.this, "POST", REST_PATH, null, com.fortmin.proshopping.logica.shopping.model.Mensaje.class);
      this.usuario = com.google.api.client.util.Preconditions.checkNotNull(usuario, "Required parameter usuario must be specified.");
      this.visible = com.google.api.client.util.Preconditions.checkNotNull(visible, "Required parameter visible must be specified.");
    }

    @Override
    public EstablecerVisibilidad setAlt(java.lang.String alt) {
      return (EstablecerVisibilidad) super.setAlt(alt);
    }

    @Override
    public EstablecerVisibilidad setFields(java.lang.String fields) {
      return (EstablecerVisibilidad) super.setFields(fields);
    }

    @Override
    public EstablecerVisibilidad setKey(java.lang.String key) {
      return (EstablecerVisibilidad) super.setKey(key);
    }

    @Override
    public EstablecerVisibilidad setOauthToken(java.lang.String oauthToken) {
      return (EstablecerVisibilidad) super.setOauthToken(oauthToken);
    }

    @Override
    public EstablecerVisibilidad setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (EstablecerVisibilidad) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public EstablecerVisibilidad setQuotaUser(java.lang.String quotaUser) {
      return (EstablecerVisibilidad) super.setQuotaUser(quotaUser);
    }

    @Override
    public EstablecerVisibilidad setUserIp(java.lang.String userIp) {
      return (EstablecerVisibilidad) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String usuario;

    /**

     */
    public java.lang.String getUsuario() {
      return usuario;
    }

    public EstablecerVisibilidad setUsuario(java.lang.String usuario) {
      this.usuario = usuario;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Boolean visible;

    /**

     */
    public java.lang.Boolean getVisible() {
      return visible;
    }

    public EstablecerVisibilidad setVisible(java.lang.Boolean visible) {
      this.visible = visible;
      return this;
    }

    @Override
    public EstablecerVisibilidad set(String parameterName, Object value) {
      return (EstablecerVisibilidad) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "getPaqueteRf".
   *
   * This request holds the parameters needed by the the shopping server.  After setting any optional
   * parameters, call the {@link GetPaqueteRf#execute()} method to invoke the remote operation.
   *
   * @param elementoRF
   * @return the request
   */
  public GetPaqueteRf getPaqueteRf(java.lang.String elementoRF) throws java.io.IOException {
    GetPaqueteRf result = new GetPaqueteRf(elementoRF);
    initialize(result);
    return result;
  }

  public class GetPaqueteRf extends ShoppingRequest<com.fortmin.proshopping.logica.shopping.model.Paquete> {

    private static final String REST_PATH = "get_paquete_rf";

    /**
     * Create a request for the method "getPaqueteRf".
     *
     * This request holds the parameters needed by the the shopping server.  After setting any
     * optional parameters, call the {@link GetPaqueteRf#execute()} method to invoke the remote
     * operation. <p> {@link
     * GetPaqueteRf#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param elementoRF
     * @since 1.13
     */
    protected GetPaqueteRf(java.lang.String elementoRF) {
      super(Shopping.this, "GET", REST_PATH, null, com.fortmin.proshopping.logica.shopping.model.Paquete.class);
      this.elementoRF = com.google.api.client.util.Preconditions.checkNotNull(elementoRF, "Required parameter elementoRF must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetPaqueteRf setAlt(java.lang.String alt) {
      return (GetPaqueteRf) super.setAlt(alt);
    }

    @Override
    public GetPaqueteRf setFields(java.lang.String fields) {
      return (GetPaqueteRf) super.setFields(fields);
    }

    @Override
    public GetPaqueteRf setKey(java.lang.String key) {
      return (GetPaqueteRf) super.setKey(key);
    }

    @Override
    public GetPaqueteRf setOauthToken(java.lang.String oauthToken) {
      return (GetPaqueteRf) super.setOauthToken(oauthToken);
    }

    @Override
    public GetPaqueteRf setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetPaqueteRf) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetPaqueteRf setQuotaUser(java.lang.String quotaUser) {
      return (GetPaqueteRf) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetPaqueteRf setUserIp(java.lang.String userIp) {
      return (GetPaqueteRf) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String elementoRF;

    /**

     */
    public java.lang.String getElementoRF() {
      return elementoRF;
    }

    public GetPaqueteRf setElementoRF(java.lang.String elementoRF) {
      this.elementoRF = elementoRF;
      return this;
    }

    @Override
    public GetPaqueteRf set(String parameterName, Object value) {
      return (GetPaqueteRf) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "getProducto".
   *
   * This request holds the parameters needed by the the shopping server.  After setting any optional
   * parameters, call the {@link GetProducto#execute()} method to invoke the remote operation.
   *
   * @param codprod
   * @return the request
   */
  public GetProducto getProducto(java.lang.String codprod) throws java.io.IOException {
    GetProducto result = new GetProducto(codprod);
    initialize(result);
    return result;
  }

  public class GetProducto extends ShoppingRequest<com.fortmin.proshopping.logica.shopping.model.ProductoVO> {

    private static final String REST_PATH = "get_producto";

    /**
     * Create a request for the method "getProducto".
     *
     * This request holds the parameters needed by the the shopping server.  After setting any
     * optional parameters, call the {@link GetProducto#execute()} method to invoke the remote
     * operation. <p> {@link
     * GetProducto#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param codprod
     * @since 1.13
     */
    protected GetProducto(java.lang.String codprod) {
      super(Shopping.this, "GET", REST_PATH, null, com.fortmin.proshopping.logica.shopping.model.ProductoVO.class);
      this.codprod = com.google.api.client.util.Preconditions.checkNotNull(codprod, "Required parameter codprod must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetProducto setAlt(java.lang.String alt) {
      return (GetProducto) super.setAlt(alt);
    }

    @Override
    public GetProducto setFields(java.lang.String fields) {
      return (GetProducto) super.setFields(fields);
    }

    @Override
    public GetProducto setKey(java.lang.String key) {
      return (GetProducto) super.setKey(key);
    }

    @Override
    public GetProducto setOauthToken(java.lang.String oauthToken) {
      return (GetProducto) super.setOauthToken(oauthToken);
    }

    @Override
    public GetProducto setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetProducto) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetProducto setQuotaUser(java.lang.String quotaUser) {
      return (GetProducto) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetProducto setUserIp(java.lang.String userIp) {
      return (GetProducto) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String codprod;

    /**

     */
    public java.lang.String getCodprod() {
      return codprod;
    }

    public GetProducto setCodprod(java.lang.String codprod) {
      this.codprod = codprod;
      return this;
    }

    @Override
    public GetProducto set(String parameterName, Object value) {
      return (GetProducto) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "getProductosPaquete".
   *
   * This request holds the parameters needed by the the shopping server.  After setting any optional
   * parameters, call the {@link GetProductosPaquete#execute()} method to invoke the remote operation.
   *
   * @param paquete
   * @return the request
   */
  public GetProductosPaquete getProductosPaquete(java.lang.String paquete) throws java.io.IOException {
    GetProductosPaquete result = new GetProductosPaquete(paquete);
    initialize(result);
    return result;
  }

  public class GetProductosPaquete extends ShoppingRequest<com.fortmin.proshopping.logica.shopping.model.ProductoCollection> {

    private static final String REST_PATH = "get_productos_paquete";

    /**
     * Create a request for the method "getProductosPaquete".
     *
     * This request holds the parameters needed by the the shopping server.  After setting any
     * optional parameters, call the {@link GetProductosPaquete#execute()} method to invoke the remote
     * operation. <p> {@link GetProductosPaquete#initialize(com.google.api.client.googleapis.services.
     * AbstractGoogleClientRequest)} must be called to initialize this instance immediately after
     * invoking the constructor. </p>
     *
     * @param paquete
     * @since 1.13
     */
    protected GetProductosPaquete(java.lang.String paquete) {
      super(Shopping.this, "GET", REST_PATH, null, com.fortmin.proshopping.logica.shopping.model.ProductoCollection.class);
      this.paquete = com.google.api.client.util.Preconditions.checkNotNull(paquete, "Required parameter paquete must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetProductosPaquete setAlt(java.lang.String alt) {
      return (GetProductosPaquete) super.setAlt(alt);
    }

    @Override
    public GetProductosPaquete setFields(java.lang.String fields) {
      return (GetProductosPaquete) super.setFields(fields);
    }

    @Override
    public GetProductosPaquete setKey(java.lang.String key) {
      return (GetProductosPaquete) super.setKey(key);
    }

    @Override
    public GetProductosPaquete setOauthToken(java.lang.String oauthToken) {
      return (GetProductosPaquete) super.setOauthToken(oauthToken);
    }

    @Override
    public GetProductosPaquete setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetProductosPaquete) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetProductosPaquete setQuotaUser(java.lang.String quotaUser) {
      return (GetProductosPaquete) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetProductosPaquete setUserIp(java.lang.String userIp) {
      return (GetProductosPaquete) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String paquete;

    /**

     */
    public java.lang.String getPaquete() {
      return paquete;
    }

    public GetProductosPaquete setPaquete(java.lang.String paquete) {
      this.paquete = paquete;
      return this;
    }

    @Override
    public GetProductosPaquete set(String parameterName, Object value) {
      return (GetProductosPaquete) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "getPuntajeCliente".
   *
   * This request holds the parameters needed by the the shopping server.  After setting any optional
   * parameters, call the {@link GetPuntajeCliente#execute()} method to invoke the remote operation.
   *
   * @param usuario
   * @return the request
   */
  public GetPuntajeCliente getPuntajeCliente(java.lang.String usuario) throws java.io.IOException {
    GetPuntajeCliente result = new GetPuntajeCliente(usuario);
    initialize(result);
    return result;
  }

  public class GetPuntajeCliente extends ShoppingRequest<com.fortmin.proshopping.logica.shopping.model.Mensaje> {

    private static final String REST_PATH = "get_puntaje_cliente";

    /**
     * Create a request for the method "getPuntajeCliente".
     *
     * This request holds the parameters needed by the the shopping server.  After setting any
     * optional parameters, call the {@link GetPuntajeCliente#execute()} method to invoke the remote
     * operation. <p> {@link GetPuntajeCliente#initialize(com.google.api.client.googleapis.services.Ab
     * stractGoogleClientRequest)} must be called to initialize this instance immediately after
     * invoking the constructor. </p>
     *
     * @param usuario
     * @since 1.13
     */
    protected GetPuntajeCliente(java.lang.String usuario) {
      super(Shopping.this, "GET", REST_PATH, null, com.fortmin.proshopping.logica.shopping.model.Mensaje.class);
      this.usuario = com.google.api.client.util.Preconditions.checkNotNull(usuario, "Required parameter usuario must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetPuntajeCliente setAlt(java.lang.String alt) {
      return (GetPuntajeCliente) super.setAlt(alt);
    }

    @Override
    public GetPuntajeCliente setFields(java.lang.String fields) {
      return (GetPuntajeCliente) super.setFields(fields);
    }

    @Override
    public GetPuntajeCliente setKey(java.lang.String key) {
      return (GetPuntajeCliente) super.setKey(key);
    }

    @Override
    public GetPuntajeCliente setOauthToken(java.lang.String oauthToken) {
      return (GetPuntajeCliente) super.setOauthToken(oauthToken);
    }

    @Override
    public GetPuntajeCliente setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetPuntajeCliente) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetPuntajeCliente setQuotaUser(java.lang.String quotaUser) {
      return (GetPuntajeCliente) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetPuntajeCliente setUserIp(java.lang.String userIp) {
      return (GetPuntajeCliente) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String usuario;

    /**

     */
    public java.lang.String getUsuario() {
      return usuario;
    }

    public GetPuntajeCliente setUsuario(java.lang.String usuario) {
      this.usuario = usuario;
      return this;
    }

    @Override
    public GetPuntajeCliente set(String parameterName, Object value) {
      return (GetPuntajeCliente) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "getVisibilidadCliente".
   *
   * This request holds the parameters needed by the the shopping server.  After setting any optional
   * parameters, call the {@link GetVisibilidadCliente#execute()} method to invoke the remote
   * operation.
   *
   * @param usuario
   * @return the request
   */
  public GetVisibilidadCliente getVisibilidadCliente(java.lang.String usuario) throws java.io.IOException {
    GetVisibilidadCliente result = new GetVisibilidadCliente(usuario);
    initialize(result);
    return result;
  }

  public class GetVisibilidadCliente extends ShoppingRequest<com.fortmin.proshopping.logica.shopping.model.Mensaje> {

    private static final String REST_PATH = "get_visibilidad_cliente";

    /**
     * Create a request for the method "getVisibilidadCliente".
     *
     * This request holds the parameters needed by the the shopping server.  After setting any
     * optional parameters, call the {@link GetVisibilidadCliente#execute()} method to invoke the
     * remote operation. <p> {@link GetVisibilidadCliente#initialize(com.google.api.client.googleapis.
     * services.AbstractGoogleClientRequest)} must be called to initialize this instance immediately
     * after invoking the constructor. </p>
     *
     * @param usuario
     * @since 1.13
     */
    protected GetVisibilidadCliente(java.lang.String usuario) {
      super(Shopping.this, "GET", REST_PATH, null, com.fortmin.proshopping.logica.shopping.model.Mensaje.class);
      this.usuario = com.google.api.client.util.Preconditions.checkNotNull(usuario, "Required parameter usuario must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetVisibilidadCliente setAlt(java.lang.String alt) {
      return (GetVisibilidadCliente) super.setAlt(alt);
    }

    @Override
    public GetVisibilidadCliente setFields(java.lang.String fields) {
      return (GetVisibilidadCliente) super.setFields(fields);
    }

    @Override
    public GetVisibilidadCliente setKey(java.lang.String key) {
      return (GetVisibilidadCliente) super.setKey(key);
    }

    @Override
    public GetVisibilidadCliente setOauthToken(java.lang.String oauthToken) {
      return (GetVisibilidadCliente) super.setOauthToken(oauthToken);
    }

    @Override
    public GetVisibilidadCliente setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetVisibilidadCliente) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetVisibilidadCliente setQuotaUser(java.lang.String quotaUser) {
      return (GetVisibilidadCliente) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetVisibilidadCliente setUserIp(java.lang.String userIp) {
      return (GetVisibilidadCliente) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String usuario;

    /**

     */
    public java.lang.String getUsuario() {
      return usuario;
    }

    public GetVisibilidadCliente setUsuario(java.lang.String usuario) {
      this.usuario = usuario;
      return this;
    }

    @Override
    public GetVisibilidadCliente set(String parameterName, Object value) {
      return (GetVisibilidadCliente) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "getpaquete".
   *
   * This request holds the parameters needed by the the shopping server.  After setting any optional
   * parameters, call the {@link Getpaquete#execute()} method to invoke the remote operation.
   *
   * @param paquete
   * @return the request
   */
  public Getpaquete getpaquete(java.lang.String paquete) throws java.io.IOException {
    Getpaquete result = new Getpaquete(paquete);
    initialize(result);
    return result;
  }

  public class Getpaquete extends ShoppingRequest<com.fortmin.proshopping.logica.shopping.model.Paquete> {

    private static final String REST_PATH = "get_paquete";

    /**
     * Create a request for the method "getpaquete".
     *
     * This request holds the parameters needed by the the shopping server.  After setting any
     * optional parameters, call the {@link Getpaquete#execute()} method to invoke the remote
     * operation. <p> {@link
     * Getpaquete#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param paquete
     * @since 1.13
     */
    protected Getpaquete(java.lang.String paquete) {
      super(Shopping.this, "GET", REST_PATH, null, com.fortmin.proshopping.logica.shopping.model.Paquete.class);
      this.paquete = com.google.api.client.util.Preconditions.checkNotNull(paquete, "Required parameter paquete must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public Getpaquete setAlt(java.lang.String alt) {
      return (Getpaquete) super.setAlt(alt);
    }

    @Override
    public Getpaquete setFields(java.lang.String fields) {
      return (Getpaquete) super.setFields(fields);
    }

    @Override
    public Getpaquete setKey(java.lang.String key) {
      return (Getpaquete) super.setKey(key);
    }

    @Override
    public Getpaquete setOauthToken(java.lang.String oauthToken) {
      return (Getpaquete) super.setOauthToken(oauthToken);
    }

    @Override
    public Getpaquete setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (Getpaquete) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public Getpaquete setQuotaUser(java.lang.String quotaUser) {
      return (Getpaquete) super.setQuotaUser(quotaUser);
    }

    @Override
    public Getpaquete setUserIp(java.lang.String userIp) {
      return (Getpaquete) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String paquete;

    /**

     */
    public java.lang.String getPaquete() {
      return paquete;
    }

    public Getpaquete setPaquete(java.lang.String paquete) {
      this.paquete = paquete;
      return this;
    }

    @Override
    public Getpaquete set(String parameterName, Object value) {
      return (Getpaquete) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "getubicacion".
   *
   * This request holds the parameters needed by the the shopping server.  After setting any optional
   * parameters, call the {@link Getubicacion#execute()} method to invoke the remote operation.
   *
   * @param ubicacion
   * @return the request
   */
  public Getubicacion getubicacion(java.lang.String ubicacion) throws java.io.IOException {
    Getubicacion result = new Getubicacion(ubicacion);
    initialize(result);
    return result;
  }

  public class Getubicacion extends ShoppingRequest<com.fortmin.proshopping.logica.shopping.model.Ubicacion> {

    private static final String REST_PATH = "get_ubicacion";

    /**
     * Create a request for the method "getubicacion".
     *
     * This request holds the parameters needed by the the shopping server.  After setting any
     * optional parameters, call the {@link Getubicacion#execute()} method to invoke the remote
     * operation. <p> {@link
     * Getubicacion#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param ubicacion
     * @since 1.13
     */
    protected Getubicacion(java.lang.String ubicacion) {
      super(Shopping.this, "GET", REST_PATH, null, com.fortmin.proshopping.logica.shopping.model.Ubicacion.class);
      this.ubicacion = com.google.api.client.util.Preconditions.checkNotNull(ubicacion, "Required parameter ubicacion must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public Getubicacion setAlt(java.lang.String alt) {
      return (Getubicacion) super.setAlt(alt);
    }

    @Override
    public Getubicacion setFields(java.lang.String fields) {
      return (Getubicacion) super.setFields(fields);
    }

    @Override
    public Getubicacion setKey(java.lang.String key) {
      return (Getubicacion) super.setKey(key);
    }

    @Override
    public Getubicacion setOauthToken(java.lang.String oauthToken) {
      return (Getubicacion) super.setOauthToken(oauthToken);
    }

    @Override
    public Getubicacion setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (Getubicacion) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public Getubicacion setQuotaUser(java.lang.String quotaUser) {
      return (Getubicacion) super.setQuotaUser(quotaUser);
    }

    @Override
    public Getubicacion setUserIp(java.lang.String userIp) {
      return (Getubicacion) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String ubicacion;

    /**

     */
    public java.lang.String getUbicacion() {
      return ubicacion;
    }

    public Getubicacion setUbicacion(java.lang.String ubicacion) {
      this.ubicacion = ubicacion;
      return this;
    }

    @Override
    public Getubicacion set(String parameterName, Object value) {
      return (Getubicacion) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "ingresoEstacionamiento".
   *
   * This request holds the parameters needed by the the shopping server.  After setting any optional
   * parameters, call the {@link IngresoEstacionamiento#execute()} method to invoke the remote
   * operation.
   *
   * @param elementoRF
   * @param usuario
   * @return the request
   */
  public IngresoEstacionamiento ingresoEstacionamiento(java.lang.String elementoRF, java.lang.String usuario) throws java.io.IOException {
    IngresoEstacionamiento result = new IngresoEstacionamiento(elementoRF, usuario);
    initialize(result);
    return result;
  }

  public class IngresoEstacionamiento extends ShoppingRequest<com.fortmin.proshopping.logica.shopping.model.Mensaje> {

    private static final String REST_PATH = "ingreso_estacionamiento";

    /**
     * Create a request for the method "ingresoEstacionamiento".
     *
     * This request holds the parameters needed by the the shopping server.  After setting any
     * optional parameters, call the {@link IngresoEstacionamiento#execute()} method to invoke the
     * remote operation. <p> {@link IngresoEstacionamiento#initialize(com.google.api.client.googleapis
     * .services.AbstractGoogleClientRequest)} must be called to initialize this instance immediately
     * after invoking the constructor. </p>
     *
     * @param elementoRF
     * @param usuario
     * @since 1.13
     */
    protected IngresoEstacionamiento(java.lang.String elementoRF, java.lang.String usuario) {
      super(Shopping.this, "POST", REST_PATH, null, com.fortmin.proshopping.logica.shopping.model.Mensaje.class);
      this.elementoRF = com.google.api.client.util.Preconditions.checkNotNull(elementoRF, "Required parameter elementoRF must be specified.");
      this.usuario = com.google.api.client.util.Preconditions.checkNotNull(usuario, "Required parameter usuario must be specified.");
    }

    @Override
    public IngresoEstacionamiento setAlt(java.lang.String alt) {
      return (IngresoEstacionamiento) super.setAlt(alt);
    }

    @Override
    public IngresoEstacionamiento setFields(java.lang.String fields) {
      return (IngresoEstacionamiento) super.setFields(fields);
    }

    @Override
    public IngresoEstacionamiento setKey(java.lang.String key) {
      return (IngresoEstacionamiento) super.setKey(key);
    }

    @Override
    public IngresoEstacionamiento setOauthToken(java.lang.String oauthToken) {
      return (IngresoEstacionamiento) super.setOauthToken(oauthToken);
    }

    @Override
    public IngresoEstacionamiento setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (IngresoEstacionamiento) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public IngresoEstacionamiento setQuotaUser(java.lang.String quotaUser) {
      return (IngresoEstacionamiento) super.setQuotaUser(quotaUser);
    }

    @Override
    public IngresoEstacionamiento setUserIp(java.lang.String userIp) {
      return (IngresoEstacionamiento) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String elementoRF;

    /**

     */
    public java.lang.String getElementoRF() {
      return elementoRF;
    }

    public IngresoEstacionamiento setElementoRF(java.lang.String elementoRF) {
      this.elementoRF = elementoRF;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String usuario;

    /**

     */
    public java.lang.String getUsuario() {
      return usuario;
    }

    public IngresoEstacionamiento setUsuario(java.lang.String usuario) {
      this.usuario = usuario;
      return this;
    }

    @Override
    public IngresoEstacionamiento set(String parameterName, Object value) {
      return (IngresoEstacionamiento) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Shopping}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Shopping}. */
    @Override
    public Shopping build() {
      return new Shopping(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link ShoppingRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setShoppingRequestInitializer(
        ShoppingRequestInitializer shoppingRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(shoppingRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
