/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-10-28 17:08:27 UTC)
 * on 2014-11-06 at 21:38:57 UTC 
 * Modify at your own risk.
 */

package com.fortmin.proshopping.logica.shopping.model;

/**
 * Model definition for EstacionamientoVO.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the shopping. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class EstacionamientoVO extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private com.google.api.client.util.DateTime actual;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private com.google.api.client.util.DateTime entrada;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Boolean presente;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private com.google.api.client.util.DateTime topSalidaGratis;

  /**
   * @return value or {@code null} for none
   */
  public com.google.api.client.util.DateTime getActual() {
    return actual;
  }

  /**
   * @param actual actual or {@code null} for none
   */
  public EstacionamientoVO setActual(com.google.api.client.util.DateTime actual) {
    this.actual = actual;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public com.google.api.client.util.DateTime getEntrada() {
    return entrada;
  }

  /**
   * @param entrada entrada or {@code null} for none
   */
  public EstacionamientoVO setEntrada(com.google.api.client.util.DateTime entrada) {
    this.entrada = entrada;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getPresente() {
    return presente;
  }

  /**
   * @param presente presente or {@code null} for none
   */
  public EstacionamientoVO setPresente(java.lang.Boolean presente) {
    this.presente = presente;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public com.google.api.client.util.DateTime getTopSalidaGratis() {
    return topSalidaGratis;
  }

  /**
   * @param topSalidaGratis topSalidaGratis or {@code null} for none
   */
  public EstacionamientoVO setTopSalidaGratis(com.google.api.client.util.DateTime topSalidaGratis) {
    this.topSalidaGratis = topSalidaGratis;
    return this;
  }

  @Override
  public EstacionamientoVO set(String fieldName, Object value) {
    return (EstacionamientoVO) super.set(fieldName, value);
  }

  @Override
  public EstacionamientoVO clone() {
    return (EstacionamientoVO) super.clone();
  }

}
