/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-07-22 21:53:01 UTC)
 * on 2014-10-25 at 03:17:37 UTC 
 * Modify at your own risk.
 */

package com.fortmin.proshopping.logica.shopping.model;

/**
 * Model definition for Ubicacion.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the shopping. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class Ubicacion extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String area;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String edificio;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String lugar;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String nombre;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer piso;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String sector;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getArea() {
    return area;
  }

  /**
   * @param area area or {@code null} for none
   */
  public Ubicacion setArea(java.lang.String area) {
    this.area = area;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getEdificio() {
    return edificio;
  }

  /**
   * @param edificio edificio or {@code null} for none
   */
  public Ubicacion setEdificio(java.lang.String edificio) {
    this.edificio = edificio;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getLugar() {
    return lugar;
  }

  /**
   * @param lugar lugar or {@code null} for none
   */
  public Ubicacion setLugar(java.lang.String lugar) {
    this.lugar = lugar;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getNombre() {
    return nombre;
  }

  /**
   * @param nombre nombre or {@code null} for none
   */
  public Ubicacion setNombre(java.lang.String nombre) {
    this.nombre = nombre;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getPiso() {
    return piso;
  }

  /**
   * @param piso piso or {@code null} for none
   */
  public Ubicacion setPiso(java.lang.Integer piso) {
    this.piso = piso;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getSector() {
    return sector;
  }

  /**
   * @param sector sector or {@code null} for none
   */
  public Ubicacion setSector(java.lang.String sector) {
    this.sector = sector;
    return this;
  }

  @Override
  public Ubicacion set(String fieldName, Object value) {
    return (Ubicacion) super.set(fieldName, value);
  }

  @Override
  public Ubicacion clone() {
    return (Ubicacion) super.clone();
  }

}
