/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-06-30 15:48:57 UTC)
 * on 2014-07-13 at 00:29:49 UTC 
 * Modify at your own risk.
 */

package com.fortmin.proshopping.shopping.model;

/**
 * Model definition for Producto.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the shopping. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class Producto extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String clave;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String codigo;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String comercio;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String nombre;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Float precio;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String producto;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getClave() {
    return clave;
  }

  /**
   * @param clave clave or {@code null} for none
   */
  public Producto setClave(java.lang.String clave) {
    this.clave = clave;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getCodigo() {
    return codigo;
  }

  /**
   * @param codigo codigo or {@code null} for none
   */
  public Producto setCodigo(java.lang.String codigo) {
    this.codigo = codigo;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getComercio() {
    return comercio;
  }

  /**
   * @param comercio comercio or {@code null} for none
   */
  public Producto setComercio(java.lang.String comercio) {
    this.comercio = comercio;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getNombre() {
    return nombre;
  }

  /**
   * @param nombre nombre or {@code null} for none
   */
  public Producto setNombre(java.lang.String nombre) {
    this.nombre = nombre;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Float getPrecio() {
    return precio;
  }

  /**
   * @param precio precio or {@code null} for none
   */
  public Producto setPrecio(java.lang.Float precio) {
    this.precio = precio;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getProducto() {
    return producto;
  }

  /**
   * @param producto producto or {@code null} for none
   */
  public Producto setProducto(java.lang.String producto) {
    this.producto = producto;
    return this;
  }

  @Override
  public Producto set(String fieldName, Object value) {
    return (Producto) super.set(fieldName, value);
  }

  @Override
  public Producto clone() {
    return (Producto) super.clone();
  }

}
