/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-06-30 15:48:57 UTC)
 * on 2014-07-13 at 00:29:26 UTC 
 * Modify at your own risk.
 */

package com.fortmin.proshopping.ubicacionendpoint;

/**
 * Service definition for Ubicacionendpoint (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link UbicacionendpointRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Ubicacionendpoint extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.16.0-rc of the ubicacionendpoint library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://fortminproshop.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "ubicacionendpoint/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Ubicacionendpoint(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Ubicacionendpoint(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "getUbicacion".
   *
   * This request holds the parameters needed by the the ubicacionendpoint server.  After setting any
   * optional parameters, call the {@link GetUbicacion#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public GetUbicacion getUbicacion(java.lang.String id) throws java.io.IOException {
    GetUbicacion result = new GetUbicacion(id);
    initialize(result);
    return result;
  }

  public class GetUbicacion extends UbicacionendpointRequest<com.fortmin.proshopping.ubicacionendpoint.model.Ubicacion> {

    private static final String REST_PATH = "ubicacion/{id}";

    /**
     * Create a request for the method "getUbicacion".
     *
     * This request holds the parameters needed by the the ubicacionendpoint server.  After setting
     * any optional parameters, call the {@link GetUbicacion#execute()} method to invoke the remote
     * operation. <p> {@link
     * GetUbicacion#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected GetUbicacion(java.lang.String id) {
      super(Ubicacionendpoint.this, "GET", REST_PATH, null, com.fortmin.proshopping.ubicacionendpoint.model.Ubicacion.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetUbicacion setAlt(java.lang.String alt) {
      return (GetUbicacion) super.setAlt(alt);
    }

    @Override
    public GetUbicacion setFields(java.lang.String fields) {
      return (GetUbicacion) super.setFields(fields);
    }

    @Override
    public GetUbicacion setKey(java.lang.String key) {
      return (GetUbicacion) super.setKey(key);
    }

    @Override
    public GetUbicacion setOauthToken(java.lang.String oauthToken) {
      return (GetUbicacion) super.setOauthToken(oauthToken);
    }

    @Override
    public GetUbicacion setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetUbicacion) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetUbicacion setQuotaUser(java.lang.String quotaUser) {
      return (GetUbicacion) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetUbicacion setUserIp(java.lang.String userIp) {
      return (GetUbicacion) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String id;

    /**

     */
    public java.lang.String getId() {
      return id;
    }

    public GetUbicacion setId(java.lang.String id) {
      this.id = id;
      return this;
    }

    @Override
    public GetUbicacion set(String parameterName, Object value) {
      return (GetUbicacion) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "insertUbicacion".
   *
   * This request holds the parameters needed by the the ubicacionendpoint server.  After setting any
   * optional parameters, call the {@link InsertUbicacion#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.fortmin.proshopping.ubicacionendpoint.model.Ubicacion}
   * @return the request
   */
  public InsertUbicacion insertUbicacion(com.fortmin.proshopping.ubicacionendpoint.model.Ubicacion content) throws java.io.IOException {
    InsertUbicacion result = new InsertUbicacion(content);
    initialize(result);
    return result;
  }

  public class InsertUbicacion extends UbicacionendpointRequest<com.fortmin.proshopping.ubicacionendpoint.model.Ubicacion> {

    private static final String REST_PATH = "ubicacion";

    /**
     * Create a request for the method "insertUbicacion".
     *
     * This request holds the parameters needed by the the ubicacionendpoint server.  After setting
     * any optional parameters, call the {@link InsertUbicacion#execute()} method to invoke the remote
     * operation. <p> {@link InsertUbicacion#initialize(com.google.api.client.googleapis.services.Abst
     * ractGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param content the {@link com.fortmin.proshopping.ubicacionendpoint.model.Ubicacion}
     * @since 1.13
     */
    protected InsertUbicacion(com.fortmin.proshopping.ubicacionendpoint.model.Ubicacion content) {
      super(Ubicacionendpoint.this, "POST", REST_PATH, content, com.fortmin.proshopping.ubicacionendpoint.model.Ubicacion.class);
    }

    @Override
    public InsertUbicacion setAlt(java.lang.String alt) {
      return (InsertUbicacion) super.setAlt(alt);
    }

    @Override
    public InsertUbicacion setFields(java.lang.String fields) {
      return (InsertUbicacion) super.setFields(fields);
    }

    @Override
    public InsertUbicacion setKey(java.lang.String key) {
      return (InsertUbicacion) super.setKey(key);
    }

    @Override
    public InsertUbicacion setOauthToken(java.lang.String oauthToken) {
      return (InsertUbicacion) super.setOauthToken(oauthToken);
    }

    @Override
    public InsertUbicacion setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (InsertUbicacion) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public InsertUbicacion setQuotaUser(java.lang.String quotaUser) {
      return (InsertUbicacion) super.setQuotaUser(quotaUser);
    }

    @Override
    public InsertUbicacion setUserIp(java.lang.String userIp) {
      return (InsertUbicacion) super.setUserIp(userIp);
    }

    @Override
    public InsertUbicacion set(String parameterName, Object value) {
      return (InsertUbicacion) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listUbicacion".
   *
   * This request holds the parameters needed by the the ubicacionendpoint server.  After setting any
   * optional parameters, call the {@link ListUbicacion#execute()} method to invoke the remote
   * operation.
   *
   * @return the request
   */
  public ListUbicacion listUbicacion() throws java.io.IOException {
    ListUbicacion result = new ListUbicacion();
    initialize(result);
    return result;
  }

  public class ListUbicacion extends UbicacionendpointRequest<com.fortmin.proshopping.ubicacionendpoint.model.CollectionResponseUbicacion> {

    private static final String REST_PATH = "ubicacion";

    /**
     * Create a request for the method "listUbicacion".
     *
     * This request holds the parameters needed by the the ubicacionendpoint server.  After setting
     * any optional parameters, call the {@link ListUbicacion#execute()} method to invoke the remote
     * operation. <p> {@link ListUbicacion#initialize(com.google.api.client.googleapis.services.Abstra
     * ctGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @since 1.13
     */
    protected ListUbicacion() {
      super(Ubicacionendpoint.this, "GET", REST_PATH, null, com.fortmin.proshopping.ubicacionendpoint.model.CollectionResponseUbicacion.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListUbicacion setAlt(java.lang.String alt) {
      return (ListUbicacion) super.setAlt(alt);
    }

    @Override
    public ListUbicacion setFields(java.lang.String fields) {
      return (ListUbicacion) super.setFields(fields);
    }

    @Override
    public ListUbicacion setKey(java.lang.String key) {
      return (ListUbicacion) super.setKey(key);
    }

    @Override
    public ListUbicacion setOauthToken(java.lang.String oauthToken) {
      return (ListUbicacion) super.setOauthToken(oauthToken);
    }

    @Override
    public ListUbicacion setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListUbicacion) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListUbicacion setQuotaUser(java.lang.String quotaUser) {
      return (ListUbicacion) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListUbicacion setUserIp(java.lang.String userIp) {
      return (ListUbicacion) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String cursor;

    /**

     */
    public java.lang.String getCursor() {
      return cursor;
    }

    public ListUbicacion setCursor(java.lang.String cursor) {
      this.cursor = cursor;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer limit;

    /**

     */
    public java.lang.Integer getLimit() {
      return limit;
    }

    public ListUbicacion setLimit(java.lang.Integer limit) {
      this.limit = limit;
      return this;
    }

    @Override
    public ListUbicacion set(String parameterName, Object value) {
      return (ListUbicacion) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "removeUbicacion".
   *
   * This request holds the parameters needed by the the ubicacionendpoint server.  After setting any
   * optional parameters, call the {@link RemoveUbicacion#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public RemoveUbicacion removeUbicacion(java.lang.String id) throws java.io.IOException {
    RemoveUbicacion result = new RemoveUbicacion(id);
    initialize(result);
    return result;
  }

  public class RemoveUbicacion extends UbicacionendpointRequest<Void> {

    private static final String REST_PATH = "ubicacion/{id}";

    /**
     * Create a request for the method "removeUbicacion".
     *
     * This request holds the parameters needed by the the ubicacionendpoint server.  After setting
     * any optional parameters, call the {@link RemoveUbicacion#execute()} method to invoke the remote
     * operation. <p> {@link RemoveUbicacion#initialize(com.google.api.client.googleapis.services.Abst
     * ractGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected RemoveUbicacion(java.lang.String id) {
      super(Ubicacionendpoint.this, "DELETE", REST_PATH, null, Void.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public RemoveUbicacion setAlt(java.lang.String alt) {
      return (RemoveUbicacion) super.setAlt(alt);
    }

    @Override
    public RemoveUbicacion setFields(java.lang.String fields) {
      return (RemoveUbicacion) super.setFields(fields);
    }

    @Override
    public RemoveUbicacion setKey(java.lang.String key) {
      return (RemoveUbicacion) super.setKey(key);
    }

    @Override
    public RemoveUbicacion setOauthToken(java.lang.String oauthToken) {
      return (RemoveUbicacion) super.setOauthToken(oauthToken);
    }

    @Override
    public RemoveUbicacion setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (RemoveUbicacion) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public RemoveUbicacion setQuotaUser(java.lang.String quotaUser) {
      return (RemoveUbicacion) super.setQuotaUser(quotaUser);
    }

    @Override
    public RemoveUbicacion setUserIp(java.lang.String userIp) {
      return (RemoveUbicacion) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String id;

    /**

     */
    public java.lang.String getId() {
      return id;
    }

    public RemoveUbicacion setId(java.lang.String id) {
      this.id = id;
      return this;
    }

    @Override
    public RemoveUbicacion set(String parameterName, Object value) {
      return (RemoveUbicacion) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "updateUbicacion".
   *
   * This request holds the parameters needed by the the ubicacionendpoint server.  After setting any
   * optional parameters, call the {@link UpdateUbicacion#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.fortmin.proshopping.ubicacionendpoint.model.Ubicacion}
   * @return the request
   */
  public UpdateUbicacion updateUbicacion(com.fortmin.proshopping.ubicacionendpoint.model.Ubicacion content) throws java.io.IOException {
    UpdateUbicacion result = new UpdateUbicacion(content);
    initialize(result);
    return result;
  }

  public class UpdateUbicacion extends UbicacionendpointRequest<com.fortmin.proshopping.ubicacionendpoint.model.Ubicacion> {

    private static final String REST_PATH = "ubicacion";

    /**
     * Create a request for the method "updateUbicacion".
     *
     * This request holds the parameters needed by the the ubicacionendpoint server.  After setting
     * any optional parameters, call the {@link UpdateUbicacion#execute()} method to invoke the remote
     * operation. <p> {@link UpdateUbicacion#initialize(com.google.api.client.googleapis.services.Abst
     * ractGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param content the {@link com.fortmin.proshopping.ubicacionendpoint.model.Ubicacion}
     * @since 1.13
     */
    protected UpdateUbicacion(com.fortmin.proshopping.ubicacionendpoint.model.Ubicacion content) {
      super(Ubicacionendpoint.this, "PUT", REST_PATH, content, com.fortmin.proshopping.ubicacionendpoint.model.Ubicacion.class);
    }

    @Override
    public UpdateUbicacion setAlt(java.lang.String alt) {
      return (UpdateUbicacion) super.setAlt(alt);
    }

    @Override
    public UpdateUbicacion setFields(java.lang.String fields) {
      return (UpdateUbicacion) super.setFields(fields);
    }

    @Override
    public UpdateUbicacion setKey(java.lang.String key) {
      return (UpdateUbicacion) super.setKey(key);
    }

    @Override
    public UpdateUbicacion setOauthToken(java.lang.String oauthToken) {
      return (UpdateUbicacion) super.setOauthToken(oauthToken);
    }

    @Override
    public UpdateUbicacion setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (UpdateUbicacion) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public UpdateUbicacion setQuotaUser(java.lang.String quotaUser) {
      return (UpdateUbicacion) super.setQuotaUser(quotaUser);
    }

    @Override
    public UpdateUbicacion setUserIp(java.lang.String userIp) {
      return (UpdateUbicacion) super.setUserIp(userIp);
    }

    @Override
    public UpdateUbicacion set(String parameterName, Object value) {
      return (UpdateUbicacion) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Ubicacionendpoint}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Ubicacionendpoint}. */
    @Override
    public Ubicacionendpoint build() {
      return new Ubicacionendpoint(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link UbicacionendpointRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setUbicacionendpointRequestInitializer(
        UbicacionendpointRequestInitializer ubicacionendpointRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(ubicacionendpointRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
